### ISSUE TITLE
[FEAT] API Endpoint For Organisation Creation by users - Backend

### ISSUE THREAD

**Issue by Cyberguru1** [hngprojects/hng_boilerplate_nestjs#102]
## Description

Develop a backend API for creating organisations, including authentication and authorization checks, input validation, and error handling.

## Acceptance Criteria

1. **Authentication Middleware**
   - Implement middleware to ensure the user is authenticated using JWT.
   - If authentication fails, return a `401 Unauthorized` status code.
   - If authenticated, proceed with the request.

2. **Create Organisation Endpoint**
   - Accepts `HTTP POST` requests at `/api/v1/organizations`.
   - Creates a new organisation with a `201 Created` status code if the user request is valid.

3. **Feild Validation**
   - Validate all supplied fields.
   - If validation fails, return a `422 Unprocessable Entity` status code with detailed error messages.

### Request Body

```json
{
  "name": "String",
  "description": "String",
  "email": "string",
  "industry": "string",
  "type": "string",
  "country": "string",
  "address": "string",
  "state": "string",

}
```

### Successful Response

```json
{
  "status": "success",
  "message": "organisation created successfully",
  "data": {
    "id": "String",
    "name": "String",
    "description": "String",
    "owner_id": "string",
    "slug" : "string",
    "email": "string",
    "industry": "string",
    "type": "string",
    "country": "string",
    "address": "string",
    "state": "string",
    "created_at": "2024-01-01T12:00:00Z",
    "updated_at": "2024-06-01T12:00:00Z"
  },
 "status_code": 201
}
```

### Unsuccessful Response

```json
{
  "status": "Bad Request",
  "message": "Client error",
  "status_code": 400
}
```

### Validation Error Response

```json
{
  "errors": [
    {
      "field": "String",
      "message": "String"
    }
  ]
}
```

### Unauthenticated Error Response

```json
{
  "status": "Unauthorized",
  "message": "User not authenticated",
  "status_code": 401
}
```

### Database Design

``` plaintext
Table organisations {
  id uuid [primary key]
  slug varchar(255) [unique]
  owner_id uuid [foreign key to users(id)]
  name varchar(255)
  email varchar(255)
  industry varchar(255)
  type varchar(255)
  country varchar(255)
  address varchar(255)
  state varchar(255)
  description text
  created_at timestamp
  updated_at timestamp
}

Table organisations_user {
  user_id uuid [foreign key to users(id)]
  organisation_id uuid [foreign key to organisations(id)]
  role varchar(255)
  created_at timestamp
  updated_at timestamp
}

Ref: users.id < organisations_user.user_id
Ref: organisations.id < organisations_user.organisation_id
```

## Purpose

Provide a backend service that allows admins to create new organisations, ensuring proper authentication, authorization, and validation.

## Requirements

- [x]   Implement middleware for  JWT authentication.
- [x]   Develop server-side logic to create a new organisation.
- [x]  Develop server-side logic to bind user to the created organisation.
- [x]   Validate each field in the request json

## Expected Outcome

The API endpoint allows users to create new organisations with appropriate validation and authentication

## Task

- [x] Create the endpoint `HTTP POST /api/v1/organizations` to create new organisations.
- [x] Implement authentication middleware to validate JWT tokens.
- [x] Validate all fields in the request body.
- [x] Write unit tests for all scenarios, including successful creation, validation errors, and authentication/authorization checks.
- [x] Perform security testing to ensure data protection and compliance.

## Testing

- Write unit tests for successful organisation creation.
- Write unit tests for fields validation.
- Write unit tests for bad client requests.
- Write unit tests for authentication checks.
- Perform security testing to ensure data protection and compliance.
- Test various scenarios for creating organisations, including edge cases and error handling.

**Comment by markessien** [comment]
Orgs are not by admin only. You need to link the org owner. Do not use nigeria specific things like LGA. Org names are not unique. You need a unique org slug

**Comment by markessien** [comment]
IS this not a duplicate?

**Comment by Cyberguru1** [comment]
we confirmed before creating, 
it's not sir

**Comment by buka4rill** [comment]
Follow this format please
https://hng11.slack.com/archives/C07C462K430/p1721213593284649

**Comment by Cyberguru1** [comment]
Updated sir @buka4rill

**Comment by Cyberguru1** [comment]
done sir @nedssoft

**Comment by NdubuisiJr** [comment]
@Cyberguru1 name should not be unique. Organisation names are not unique

**Comment by Cyberguru1** [comment]
Update it sir @NdubuisiJr

**Comment by Cyberguru1** [comment]
Test case done by QA tester [link](https://docs.google.com/spreadsheets/d/1PIhLrdj7d1pS2-rHe4RfxrGGq_k-xFDambX1G_mD_eg/edit?gid=1979456619#gid=1979456619)
