### ISSUE TITLE
[FEAT] Product Search Endpoint - BACKEND

### ISSUE THREAD

**Issue by blessingtutka** [hngprojects/hng_boilerplate_nestjs#105]
## Description

This feature involves creating a product search endpoint for the backend system. The endpoint will allow users to search for products by name, category, and price range. Additional search features can be added to enhance the functionality.

## Acceptance Criteria

- Users can search for products by name.
- Users can search for products by category.
- Users can filter search results by price range.
- The endpoint should return accurate search results based on the given criteria.
- The search functionality should be efficient and performant, even with a large dataset.
- Proper error handling and validation should be implemented for search queries.

## Purpose

This feature aims to provide users with a robust and flexible product search capability, making it easier for them to find specific products based on various criteria. This will improve the overall user experience and increase the application's usability.

## Requirements	

- Implement a RESTful endpoint for product search.
- Use appropriate query parameters to handle search criteria (name, category, price range).
- Integrate with the existing product database to fetch and filter results.
- Ensure the endpoint adheres to best practices for API design and security.
- Write unit and integration tests to validate the functionality and performance of the endpoint.

### URL
```bash
/api/v1/products/search
```

### METHOD
```
GET
```
### Query Parameters
- `name (optional)`: The name of the product to search for.
- `category (optional)`: The category of the product to search for.
- `minPrice (optional)`: The minimum price of the product to search for.
- `maxPrice (optional)`: The maximum price of the product to search for.

### Example Request

```GET /api/v1/products/search?name=t-shirt&category=kids&minPrice=100&maxPrice=1000```

#### Success Response(json)
```json
{
  "success": true,
  "statusCode":200,
  "products": [
    {
      "id": 1,
      "name": "White T-shirt with image",
      "category": "kids",
      "price": 200,
      "description": "A white T-shirt with tom and jerry image ",
      "imageUrl": "http://example.com/images/white_t_shirt_tom_jerry_image.jpg"
    },
    {
      "id": 2,
      "name": "Black T-shirt",
      "category": "kids",
      "price": 150,
      "description": "A Black t-shirt",
      "imageUrl": "http://example.com/images/black_t_shirt.jpg"
    }
  ]
}

```
#### Empty Response(json)
```json
{
  "success": true,
  "products": [],
  "statusCode":204
}
```
#### Validation Error Response(json)
```json
{
  "success": false,
  "errors": [
    {
        "parameter":"name",
        "message":"name is  a required parameter"
    }
  ]
  "statusCode":422
}
```
#### Bad Request Response(json)
```json
{
  "success": false,
  "message": "Bad Request",
  "statusCode":400
}
```
#### Error Response(json)
```json
{
  "success": false,
  "message": "Server Error",
  "statusCode":500
}
```

## Task

- [ ] Design the product search endpoint.
- [ ] Implement query parameters for name, category, and price range.
- [ ] Integrate the search endpoint with the existing product database.
- [ ] Implement error handling and validation for search queries.
- [ ] Write unit tests for the search functionality.
- [ ] Write integration tests for the search endpoint.
- [ ] Document the API endpoint and usage.

## Expected Outcome

- A functional product search endpoint that meets all acceptance criteria.
- Users can efficiently search for products using various criteria.
- The search results are accurate and relevant to the user's query.
- The system handles a high volume of search requests without significant performance degradation.
