### ISSUE TITLE
[FEAT] Manage Organizations API - BACKEND

### ISSUE THREAD

**Issue by aniebietafia** [hngprojects/hng_boilerplate_nestjs#114]
## Description
Implement the functionality to manage organization.

## Acceptance Criteria
- The endpoint should be accessible at `/api/organization/:orgId/manage`.
- The endpoint should accept http `PUT` requests.
- Fetches Organisation Id from the request params.
- The endpoint can only be accessed by authenticated users.
- The endpoint can only be accessed by an admin.
- Valid authentication (e.g. JWT or Social signin) in the Authorization header to be able to access the endpoint.
  - `Authorization: Bearer <token>`
- An admin should use the endpoint to rename, archive, activate and deactivate an organization. 

#### Manage organization endpoint `/api/organization/:orgId/manage [PUT]`
- Request Body
```
{
 orgName: "New name",
 isArchived: boolean,
 isActivated: boolean,
 isDeactivated: boolean
}
```
- Response Body
```
{
 status_code: 200,
 message: "Update successful",
 payload: {
   id: "46575-sg46yhe-78dgr654-ehy673nmd45",
   orgName: "New name",
   isArchived: true,
   isActivated: false,
   isDeactivated: true
  }
}
```

#### Validation
- The userId must be fetched from the user object after a successful authentication.
- Checks must be done to verify that the user is successfully logged in and is an admin.
- If the user is not an admin, it should throw a 401 (Unauthorized) error.
 ```
  {
    status_code: 401,
    message: "You're not authorized to perform this action,
    error: Unauthorized
  }
 ```

### Purpose
Provide functionality for renaming, archiving, activating, and deactivating an organization.

### Requirem#ents
- Functional API endpoints to support managing organizations.
- User must be an admin to access the endpoint.
- Admin must be authenticated to access the endpoint.	

### Expected Outcome
- Admins can manage organizations via the API.

### Tasks

- [ ] Create endpoints to allow admin manage organizations.
- [ ] Ensure that the user is logged in and has a valid token to access the endpoints.
- [ ] Ensure that the user is an admin to access the endpoint.
- [ ] Implement server-side logic to handle validations.
- [ ] Write unit tests for renaming, archiving, activating, and deactivating organizations.
- [ ] Write integration test to ensure successful actions.

### Testing
- Unit tests for Backend validations.
- Integration test for e-to-e manage actions.
- Security testing to ensure user has a valid token and is an admin.

**Comment by markessien** [comment]
unclear what this is admin and not on the org api

**Comment by aniebietafia** [comment]
The endpoint has been fixed. It is to manage Organisations by renaming, activating, deactivating and archiving an organization.

**Comment by markessien** [comment]
does not make sense as a separate endpoint
