### ISSUE TITLE
[FEAT]: Implement API Endpoint For Language Selection

### ISSUE THREAD

**Issue by SamixYasuke** [hngprojects/hng_boilerplate_nestjs#115]
### Description
Implement a backend API to manage language preferences for users. This API will enable users to choose their preferred language.

### Acceptance Criteria
- Implement a POST endpoint accessible at `/api/user/settings/language` to save the selected language for a user
- Validate the `language_code` against a predefined list of supported languages
- Implement JWT auth token validation
- Ensure requests to `/api/user/settings/language` include a valid JWT auth token in the `Authorization` header
- Use ISO 639-1 standard for the language format
- Return appropriate error messages and status codes for invalid inputs and system errors

### Database Schema
```sql
CREATE TABLE UserLanguagePreferences (
    userId VARCHAR(255) PRIMARY KEY,
    languageCode VARCHAR(10)
);
```

#### [POST] `/api/user/settings/language`
**Request Body:**
```json
{
  "user_id": "string",
  "language_code": "string"
}
```
**Response:**
```json
{
  "message": "Language preference updated successfully",
  "data": {
    "user_id": "string",
    "language_code": "string"
  }
}
```

### Validation
- Validate `language_code` against a predefined list of supported languages.

### JWT Authentication
Implement JWT auth token validation.

### Error Handling
Example error response for unsupported language:
```json
{
  "message": "Unsupported language code",
  "error": "Bad Request",
  "status_code": 400
}
```

### Purpose
To allow users to choose and update their preferred language for a personalized experience across the application

### Expected Outcome
A fully functional backend API that allows users to save and retrieve their language preferences

### Tasks
- [ ] Implement the POST endpoint to save language preference
- [ ] Validate inputs and handle errors properly
- [ ] Write unit tests for endpoints to ensure they handle valid and invalid inputs correctly

###Testing
- Unit tests for the endpoint to ensure it handles valid and invalid inputs properly

**Comment by bolexs** [comment]
@buka4rill what do you think about this?

**Comment by SamixYasuke** [comment]
[This is the correction from ticket #28 that was misunderstood as a frontend ticket](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/28)

**Comment by buka4rill** [comment]
This is not how to implement a feature like this.
- you would need some kind of language api
- when a user selects for example, the whole data is returned in spanish

This is broad and I would discard this for boilerplate

**Comment by SamixYasuke** [comment]
@buka4rill this feature is just to know the user's language preference and save that data. Would you like me to redo it your way?
