### ISSUE TITLE
[FEAT] Implement Organization Deletion

### ISSUE THREAD

**Issue by Heba-WebDev** [hngprojects/hng_boilerplate_nestjs#126]
### Description

Create an API endpoint to handle the deletion of an organization. This endpoint will validate the organization ID and update the specified organization deleted attribute to true in the database upon successful validation.

### Acceptance Criteria

- The endpoint should be accessible at `/api/v1/organizations/:org_id`.
- The endpoint should accept HTTP DELETE requests.
- The endpoint should be protected and require authentication.
- The endpoint should check that the user hitting the endpoint is the owner of the organization.
- Requests to the endpoint must include a valid authentication token in the Authorization header. Authorization: ```Bearer <token>```
- Upon successful validation of the organization ID, the organization should be marked as deleted by changing `deleted` attribute in the database to `true`.
- All related data to the organization should remain intact.

#### Data Validation and Sanitization:

- The API should validate the request to ensure the organization ID is present and valid.
- The organization ID should be checked for correctness and validity (e.g., it exists in the system).
- The API should verify that the authenticated user is the owner of the organization.

### Request
Endpoint DELETE /api/v1/organizations/:org_id

#### Request example:
```http
DELETE /api/v1/organizations/:org_id
Content-Type: application/json
Authorization: Bearer <token>

```

#### Expected Successful Response:

204 No Content status code

#### Expected Error Response:

```json
{
  "message": "Failed to delete organization",
  "error": "Invalid organization ID format",
  "status_code": 400
}
```
```json
{
  "message": "Failed to delete organization",
  "error": "Invalid organization ID",
  "status_code": 404
}
```
```json
{
  "message": "Failed to delete organization",
  "error": "User not authorized to delete this organization",
  "status_code": 401
}
```

### Purpose

Provides a backend service to handle the deletion of organizations, ensuring the organization ID is valid and setting the organization `deleted` attribute to `true`  in the database.

### Tasks

- [ ] Develop server-side logic to handle organization deletion requests.
-  [ ] Validate and sanitize incoming organization ID data.
-  [ ] Validate the user deleting the organization is the owner.
- [ ] Change the specified organization`deleted` attribute upon successful validation to `true` in the database.
- [ ] Keep all related data of the specified organization intact.

### Testing

1 - Write unit tests to ensure the organization deletion endpoint validates input correctly and removes the organization from the system.
2 - Test various scenarios for submitting the organization ID (e.g., valid ID, non-existent ID, malformed ID, etc.).

**Comment by markessien** [comment]
should be soft delete

**Comment by Heba-WebDev** [comment]
Updated

**Comment by Shullyd7** [comment]
Add versioning to your endpoint e.g /api/v1/organizations
Use snake case for OrgId

**Comment by Heba-WebDev** [comment]
@Shullyd7 Updated!

**Comment by Shullyd7** [comment]
Why is the org_id in the request body and not path variable?

**Comment by Heba-WebDev** [comment]
@Shullyd7 Changed to path variable
