### ISSUE TITLE
[FEAT] External Dynamic Pages > Blog Post header

### ISSUE THREAD

**Issue by kleenpulse** [hngprojects/hng_boilerplate_nestjs#127]
## Description
Develop a reusable Blog Post Header component. This component will be used at the top of individual blog post pages. The Blog Post Header should be visually appealing, responsive, and should include the following elements:

## Acceptance Criteria
- Implementation must be responsive
- All buttons should be functional
- Implementation must be pixel perfect

### Requirements	
The component should receive the following props:

- Title
- Subtitle
- Date
- Author name
- Author profile picture
- Tag
- Time of reading
- Blog Image (background image or main image)
- Excerpt

### Testing

- Ensure the component is responsive and renders correctly with all required elements
- Check that the component handles any length of texts (long titles, missing images) no weird layout shifts.

### Tasks

- [ ]  Develop the Blog Post Header component based on the provided requirements.
- [ ] Design both portrait and landscape versions.
- [ ] Run tests to ensure the component works as expected.

# Link
[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=10-23157&m=dev).
### 
![image](https://github.com/user-attachments/assets/e85fab36-1a66-48f7-9966-6293fd58cc39)

**Comment by markessien** [comment]
this is a FE ticket
