### ISSUE TITLE
[FEAT] Fetch Customer Details

### ISSUE THREAD

**Issue by Bola-coder** [hngprojects/hng_boilerplate_nestjs#129]
## Description
Create an API endpoint to fetch detailed information about a specific customer by ID with proper authentication and validation.

## Acceptance Criteria

- The endpoint should be accessible at api/v1/customers/{id}.
- The endpoint should accept HTTP GET requests.
- The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access customer details.
- Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
- Requests to the endpoint must include a valid authentication token in the Authorization header: Authorization: Bearer <token>.

**Request:**

- The customer ID should be included in the URL path.
- No request body is required.

**Response:**

- On successful retrieval of customer details, the API should return a 200 OK status code with the customer data.

`
{
  "status_code": 200,
  "data": {
    "id": "12345",
    "name": "John Doe",
    "email": "john.doe@example.com",
    "phone": "123-456-7890",
    "address": "123 Main St, Anytown, USA",
    "created_at": "2023-01-01T00:00:00Z",
    "updated_at": "2023-07-18T00:00:00Z"
  }
}
`

**Error Handling:**
- If the customer is not found, the API should return a 404 Not Found status code.

`
{
  "status_code": 404,
  "message": "Customer not found",
  "error": "Not Found"
}
`

- If the user is not authenticated, return a 401 Unauthorized status code.
`
{
  "status_code": 401,
  "message": "Authentication required",
  "error": "Unauthorized"
}
`
- If the user does not have permission to access customer details, return a 403 Forbidden status code.
`
{
  "status_code": 403,
  "message": "You do not have permission to access this customer's details",
  "error": "Forbidden"
}
`
- If there's a server error, return a 500 Internal Server Error status code.
`
{
  "status_code": 500,
  "message": "An unexpected error occurred",
  "error": "Internal Server Error"
}
`

### Purpose
Provides a backend service that allows authorized users to retrieve detailed customer information for the Customer Details Page.

### Requirements	
- Develop server-side logic to fetch customer details by ID.
- Ensure only users with appropriate permissions can access customer details.
- Implement proper error handling and status code responses.

### Expected Outcome
API endpoint allows retrieval of customer details with appropriate authentication and error handling.

### Task

- [ ] Create an endpoint GET /api/customers/{id} to fetch customer details.
- [ ] Implement server-side logic to handle successful and failed customer detail retrieval requests.
- [ ] Ensure the user has the proper permissions to access customer details.
- [ ] Implement proper error handling for various scenarios (customer not found, unauthorized access, etc.).
- [ ] Write unit tests for the fetch customer details functionality.
- [ ] Write integration tests for fetching customer details.
- [ ] Perform security testing to ensure only authorized users can access customer details.

### Testing
- Write unit tests for the fetch customer details logic.
- Write integration tests for the end-to-end fetch customer details flow.
- Test Fetching details of an existing customer.
- Test Attempting to fetch details of a non-existent customer.
- Test Attempting to fetch customer details without authentication.
-  Test Attempting to fetch customer details without proper permissions.

###

**Comment by markessien** [comment]
Unclear what a customer is

**Comment by Bola-coder** [comment]
A customer is a user we are providing service to in any form or capacity

**Comment by Shullyd7** [comment]
Specify the response payload for all the error handling

**Comment by Shullyd7** [comment]
Specify all the response payload for the error handling and for successful retrieval(include pagination if needed)

**Comment by highb33kay** [comment]
Waiting @Bola-coder 

> Specify all the response payload for the error handling and for successful retrieval(include pagination if needed)

**Comment by Shullyd7** [comment]
Be consistent with using snake case.
statusCode should be status_code, updatedAt should be updated_at and so on @Bola-coder

**Comment by Bola-coder** [comment]
Fixed that @Shullyd7 @highb33kay
