### ISSUE TITLE
[FEAT]: Implement API Endpoint for Adding Blog Categories

### ISSUE THREAD

**Issue by GreyyDaze** [hngprojects/hng_boilerplate_nestjs#142]
## Description
Develop backend logic to securely handle adding blog categories by superadmins. The API should allow superadmins to create new categories for organizing blog posts.

### Blog Category Creation:
- Implement server-side logic to add new blog categories.
- Restrict category creation capabilities to users with a super admin role.
- Authentication via token is required to access the category creation functionality.

### Validation and Sanitization:
- Validate and sanitize incoming category data to prevent injection attacks and ensure data integrity.

### Data Storage:
- Securely store new blog category details in the database, adhering to best practices for data security.

### Response Handling:
- Return appropriate success or error messages based on the outcome of the category creation process.
- Ensure error messages do not expose sensitive information and are handled gracefully.

## Purpose
Enhance backend functionality for adding blog categories securely, enabling superadmins to organize blog posts effectively with strict access control enforced via token authentication.

## Requirements
- [ ] Develop secure server-side endpoints (`/api/blog-categories`) to handle the creation of blog categories, requiring token authentication.
- [ ] Implement validation and sanitization of incoming data to prevent security vulnerabilities.
- [ ] Ensure new blog category details are securely stored in the database with role-based access control and token verification.
- [ ] Handle and return appropriate responses for successful and failed category creation requests, enforcing token-based authentication and role restrictions.

## Expected Outcome
The backend should securely manage the creation of blog categories, providing reliable functionality for superadmins to organize blog posts effectively with strict access control enforced via token authentication throughout the process.

## Endpoint
**Create Blog Category**

**Description:** Handles requests to create new blog categories.

**Endpoint:** `POST /api/blog-categories`

**Request Body:**
```json
{
  "name": "String"
}
```
**Error Response:**
```json
{
  "message": "String",
  "error": "String",
  "statusCode": number
}
```
**Database Schema:**

**Table Name: `blog_categories`**

| Column Name | Data Type | Description                                      |
|-------------|-----------|--------------------------------------------------|
| `id`        | Number   | Primary key, auto-generated ID for the category. |
| `name`      | String    | Name of the blog category.                       |
| `createdAt` | Timestamp | Timestamp when the category was created.         |
| `updatedAt` | Timestamp | Timestamp when the category was last updated.    |

## Tasks

- [ ] Implement a secure POST endpoint (`/api/blog-categories`) to handle requests for creating blog categories, requiring token authentication.
- [ ] Validate and sanitize incoming data (category name) to prevent security vulnerabilities.
- [ ] Securely store new blog category details in the database with role-based access control and token verification.
- [ ] Handle and return appropriate success or error messages for category creation operations, ensuring token-based authentication and role restrictions are enforced.

## Testing

- Write unit tests to validate the functionality of the secure blog category creation endpoint, including successful creations and error handling for failed creations.
- Test token authentication and role-based access control mechanisms to ensure only superadmins with valid tokens can perform category creation operations.
- Perform integration testing to validate end-to-end functionality of the secure blog category creation process, focusing on data validation, storage, and authentication.

**Comment by Shullyd7** [comment]
Your error response is too vague.
Also, is number a datatype?

**Comment by GreyyDaze** [comment]
You are correct, mentor. I have updated the error response as suggested. Regarding the datatype, I used Number for platform agnosticism but have now changed it back to INTEGER.

I have made the changes as advised, @Shullyd7 . Kindly review them again.

**Comment by GreyyDaze** [comment]
Team Members

@Akinyeleib Spring Boot
@Kelviz FastAPI
@joemickie .NET
@GreyyDaze Nestjs
@charlesmbuu Laravel
