### ISSUE TITLE
[FEAT]: Authentication - User Log Out

### ISSUE THREAD

**Issue by trevorjob** [hngprojects/hng_boilerplate_nestjs#149]
## Description
Develop a new API endpoint to handle user logout. The endpoint should invalidate the user's authentication token, effectively logging them out of the system. It should handle invalid or missing tokens gracefully by returning appropriate error messages. Additionally, ensure that the token invalidation process is secure and that tests are implemented to verify functionality.
## Acceptance Criteria
- [ ] The endpoint must return a 422 error for missing or invalid input with an appropriate error message.
- [ ] A 401 status code should be returned for invalid token with an appropriate error message.
- [ ] A successful logout should return a 200 response with a success message.
- [ ] User's session token must be invalidated.
- [ ] Proper handling of any token-related errors with appropriate status codes and messages.

### Purpose
To provide a secure and standardized method for users to log out, ensuring that their authentication token is invalidated and cannot be used to access protected resources. This includes implementing a robust token invalidation process and ensuring thorough testing.

### Requirements	
- **Endpoint:** ``` /api/v1/auth/logout ```
- **HTTP Method:** POST
- **Headers:**
```
Headers: {
  "Authorization": "Bearer <token>",
  "Content-Type: application/json"
}
```
- **Success Response (200):**
```
{
  "message": "Logout successful."
}
```
- **Error Response (400):**
```
{
  "error": "Invalid request",
  "message": "Authentication token is required."
}
```
### Token Invalidation Logic
- Invalidate the JWT token by adding it to a blacklist or updating its status in the database.
- Ensure the token can no longer be used for authentication.
### Testing
- **Unit Tests**
  1. **Valid Token:**
      * Ensure a valid token results in a 200 status and a success message.
  2. **Invalid or Missing Token:**
      * Ensure missing token results in a 400 status and the appropriate error message.
      * Ensure an invalid token results in a 400 status and the appropriate error message.
- **Integration Tests:**
  1. **Token Invalidation:**
      * Verify that the endpoint correctly invalidates the token.
      * Ensure the invalidated token cannot be used for future authentication.
### Tasks
1. **Develop API Endpoint:**
    - [ ] Implement the ``` /api/v1/auth/logout ``` endpoint.
    - [ ] Ensure it correctly processes the request and invalidates the token.
    - [ ] Handle missing or invalid tokens appropriately.
2. **Integrate Token Invalidation Logic:**
    - [ ] Implement the logic to invalidate tokens (e.g., add to blacklist or update status in the database).
    - [ ] Ensure secure handling of tokens.
3. **Implement Tests:**
    - [ ] Write unit tests to cover all cases (valid token, invalid token, missing token).
    - [ ] Write integration tests to ensure token invalidation and future prevention of its use.
4. **Documentation:**
    - [ ] Document the API endpoint, including request/response bodies, success, and error codes.
    - [ ] Ensure the documentation is accessible and understandable for future developers.
5. **Code Review and Testing:**
    - [ ] Conduct a code review to ensure best practices and security measures.
    - [ ] Perform thorough testing to ensure the endpoint works as expected.
6. **Deployment:**
    - [ ] Deploy the endpoint to the appropriate environment.
    - [ ] Ensure the necessary configurations and environment variables are set for JWT and database connections.

### Expected Outcome
A functional API endpoint that allows users to log out by invalidating their authentication token. The endpoint will enhance security by ensuring that logged-out tokens cannot be used to access protected resources. Tests will ensure the endpoint functions correctly and securely.

**Comment by trevorjob** [comment]
@markessien i can't seem to add labels anymore
