### ISSUE TITLE
[FEAT]: Retrieve Product Details- Backend

### ISSUE THREAD

**Issue by ZEED2468** [hngprojects/hng_boilerplate_nestjs#152]
**Description:**
Develop a backend API endpoint to allow logged-in users to retrieve the details of a specific product. This functionality is part of the product management system and requires user authentication.

**Acceptance Criteria:**

**Endpoint security:**

Only authenticated users can have access to the endpoint
A user must have the appropriate permissions to access the endpoint
Each request to the endpoint must include a valid authentication token in the

**1. Retrieve Product Details:**
- **Method:** GET
- **URL:** `/api/v1/products/:id`
- **Request:**
  - **Headers:**
    - `Authorization: Bearer <JWT_token>`
- **Response:**
  **On successful retrieval:**
  ```json
  {
    "status": "success",
    "message": "Product details retrieved successfully",
    "status_code": 200,
    "data": {
      "id": 1,
      "name": "string",
      "price": 45.0
      "description": "string",
    }
  }
  ```

  **On error (e.g., product not found):**
  ```json
  {
    "status": "error",
    "message": "Product not found",
    "status_code": 404
  }
  ```

  **On error (e.g., unauthorized access):**
  ```json
  {
    "status": "error",
    "message": "Unauthorized access",
    "status_code": 401
  }
  ```

**Validation:**
- Validate the JWT auth token.
- Validate that the `id` exists and the user is authorized to view the product.

**Purpose:**
To provide a secure and authenticated endpoint for retrieving details of a specific product, ensuring only authorized users can access this information.

**Expected Outcome:**
A fully functional backend API endpoint that allows logged-in users to retrieve product details, with proper validation and error handling.

**Tasks:**

- [ ] Implement the GET endpoint to retrieve product details.
- [ ] Validate inputs and handle errors appropriately.
- [ ] Write unit tests for the endpoint to ensure it handles valid and invalid inputs correctly.

**Test Scenarios:**
1. **Successful product retrieval:** Verify that a logged-in user can retrieve product details with a valid product ID.
2. **Product not found:** Verify that the endpoint returns a 404 status code when the product does not exist.
3. **Unauthorized access:** Verify that the endpoint returns a 401 status code when the user is not authorized to view the product.
4. **Validation error:** Verify that the endpoint returns a 400 status code when required parameters are missing or incorrectly formatted.

**Comment by ZEED2468** [comment]
The deletion should be easier

**Comment by markessien** [comment]
this appears to be duplicated. If it is the same as the old one, then the old one is the valid one

**Comment by ZEED2468** [comment]
No  the ones I can see is just receiving user's organisation. Mine is retrieve users organisation with pagination 
#79 and #147

**Comment by ZEED2468** [comment]
No the other one is to retrieve organisation, mine is to retrieve organisation with pagination does it mean is still the same???

**Comment by ZEED2468** [comment]
The other retrieve organisation didn't have pagination so I decided to
create an issue that while retrieving an organisation there should a
certain number of organisation per page

**Comment by Hardeezah** [comment]
This is a duplicate of mine #154

**Comment by ZEED2468** [comment]
Created a new issue

**Comment by ZEED2468** [comment]
I've created a new issue from a suggestion from Mark suggestions

**Comment by ZEED2468** [comment]
After noticing this is a duplicate issue, I edited the issue title and comment to the new issue entirely from Mark’s suggestions this morning.
I removed the "Approved -1st Mentor" label to get approved so that Mark can review it again.

**Comment by Shullyd7** [comment]
Why did you remove the Approved -1st Mentor" label?
Get that label first from Mark

**Comment by ZEED2468** [comment]
I removed it because the Approved -1st Mentor label was for an issue that was a duplicate 
So I edited it the way Mark told me this morning in the meeting and removed the label so he can review it again.

**Comment by ZEED2468** [comment]
I'm sorry Mark for the edits, all I'm trying to do is to avoid a duplicate.

After noticing this is a duplicate issue, I edited the issue title and comment to the new issue entirely from Mark’s suggestions this morning.
I removed the "Approved -1st Mentor" label to get approved so that Mark can review it again.

**Comment by ZEED2468** [comment]
I can't assign my other team members I can only assign myself @ZEED2468 

**TEAM UZI**

**@theijhay  FastApi
@sparkybug laravel**
