### ISSUE TITLE
[FEAT] Update User Profile 

### ISSUE THREAD

**Issue by TheCodeGhinux** [hngprojects/hng_boilerplate_nestjs#163]
## Description
Create an API endpoint to update user profile. It updates the user profile information of an authenticated user

## Acceptance Criteria
The endpoint should be accessible at  api/user/:id.
The endpoint should accept HTTP PUT requests.
The endpoint should be secured to ensure that only authenticated users can update their settings.
Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
Requests to the endpoint must include a valid authentication token in the Authorization header. Authorization: Bearer <token>
- Header
```
{
  "Authorization": "Bearer eyJhbGciOiJIUzI1N...."
}
```

- Request Body
```
PUT /api/user/213
{
  email: "ayomide@url.com",
}
```

- Response
On a successful update of the user, the API should return a 200 OK status code.
The response body should contain the newly updated user details.
```
{
  "message": "user profile retrieved successfully",
  "user": {
    "id": "213",
    "firstName": "John",
    "lastName": "Doe",
    "email": "ayomide@url.com",
  },
}
```
- Authentication Error
```
{
  "statusCode": 401,
  "error": "invalid authentication token",
  "message": "user not authorized for this action",

}
```
- Invalid User Error
```
{
  "statusCode": 404,
  "error": "not found error",
   "message": "user not found",
}
```
- Validation
If any required field is missing or invalid, the response should return a 400 Bad Request status code with appropriate validation error messages.
```
{
  statusCode: 400,
  message: ["email must be a string"],
  error: "Bad Request"
}
```
### Purpose
It allows authenticated users to update their personal information in the application's database. This typically includes fields such as username, email, first name, last name, and other profile-related details.

### Requirements

- [ ] Authenticate  user for the action
- [ ] Authorize user for the action
- [ ] Develop server-side logic to handle user profile update.
- [ ] Validate user data
- [ ] Update only validated fields provided in body
- [ ] Ensure compliance with security standards for handling user information.

### Expected Outcome
1. Successful Update: The endpoint changes the user's database profile information and gives a success response if the user is authenticated and submits accurate data.
2. Authentication Errors: The endpoint returns an authentication error if the user is not authenticated or if their session has expired.
3. Validation Errors: The API returns the relevant error messages if the provided data does not pass validation checks (for example, an invalid email format).

### Task

 Create a PUT endpoint  /api/users/:id to update user profile
 Implement server-side logic to handle successful and failed update request.
 Ensure the user has the proper permissions and authentication to update profile
 Write unit tests for  updating user profile.
 Write integration tests for updating user profile.
 Perform security testing to ensure data protection and compliance.

### Testing

- [ ] Write integration testing end-to-end test for updating user data
- [ ] Write unit tests for various edge cases and error handling scenarios.
- [ ] Perform security testing to ensure data protection and compliance.
- [ ] Test various scenarios updating user profile

**Comment by markessien** [comment]
I see no need for a separate route for this outside of the normal user update

**Comment by TheCodeGhinux** [comment]
It would be closed
