### ISSUE TITLE
[FEAT]: Retrieving a Single Post Content

### ISSUE THREAD

**Issue by WaveGuide1** [hngprojects/hng_boilerplate_nestjs#164]
## Description
Create API endpoints to retrieve post content that will provide the necessary data for the front-end content view page.

## Acceptance Criteria
- **The endpoint should be accessible at `/api/posts/{Id}`**
- **The endpoint should accept HTTP GET request**
- **The endpoint should be secure to ensure that authenticated user with appropriate permission can have access to retrieve content.**
- **Proper authentication mechanism (eg. JWT) should be implemented**
- **Request to the endpoint must include a valid authentication token in authorisation header. Authorisation: Bearer <token>**

### Request
- **The content id should be included in the URL path**
- **No request body is required**

### Response
On successful GET request of a content the API should return a 200 success status code

```json
    {
  "status": "success",
  "data": {
    "comments": [
      {
        "commentId": "1",
        "postId": "123",
        "content": "This is a comment.",
        "author": "Commenter Name",
        "createdAt": "Date",
        "updatedAt": "Date"
      },
      {
        "commentId": "2",
        "postId": "123",
        "content": "This is another comment.",
        "author": "Another Commenter",
        "createdAt": "Date",
        "updatedAt": "Date"
      }
    ],
    "reactions": {
      "likes": 11,
      "dislikes": 2,
      "hearts": 5
    }
  }
}
 ```
### Error Handling
- If the user is not authenticated return a 401 Unauthorised status code
- If the user do not have permission to get the content of a post return 403: Forbidden status code
- If the post does not exist return a 404 Not Found status code
- If there is a server error return a 500 Internal Server Error status code

Explain

```json
     {
       "status": "404",
       "message": "The content your are trying to get does not exist"
       "error": "Not Found"
     }
 ```

### Purpose
- To provide the necessary data for the frontend content view page.
- To ensure only users with appropriate permission can request for the post content
- Implement proper error handling and status code responses

### Expected Outcome
- API that deliver post contents efficiently 

### Task
- Implement content retrieval endpoint  GET /api/posts/{Id}
- Implement server-side logic to handle successful and failed GET post content request
- Ensure the user have the proper permission to get post content
- Implement proper error handling of various scenarios (Post not found, Unauthorised access etc)
- Write unit test for the GET post content functionality
- Write integration test for getting a post content
- Perform Security testing to ensure only authorised users can get a post content

### Testing
- Write unit test for the get post content logic
- Write integration test for the end to end get post content flow
- Test various scenarios 
  - [ ] Getting an existing post content
  - [ ] Attempting to get a non-existence content
  - [ ] Attempting to get a post content without authentication
  - [ ] Attempting to get a post content without proper permission
- Perform security testing to ensure only authorised user can get post content

**Comment by WaveGuide1** [comment]
TEAM CODERS PRO
Members:

@Poche - Nest.js
@Esther Linus - Java
@Ancestor - Python

**Comment by posh1001** [comment]
@poche - Nest.js Retrieving a single post content

**Comment by NecyNazy** [comment]
@Esther- Java Dev

**Comment by markessien** [comment]
this does not seem like a real ticket. What is a post? If it's blog, I think this is done already
