### ISSUE TITLE
[FEAT] Update Organization

### ISSUE THREAD

**Issue by TheCodeGhinux** [hngprojects/hng_boilerplate_nestjs#166]
## Description
Create an API endpoint to update organization. It updates the details of an organization.

## Acceptance Criteria
The endpoint should be accessible at /api/v1/organizations/{organization-id}
The endpoint should accept HTTP PUT requests.
The endpoint should be secured to ensure that only authenticated and authorized users can update the organization details.
Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
Requests to the endpoint must include a valid authentication token in the Authorization header. Authorization: Bearer <token>

### Request

- **Endpoint**
 Endpoint:  `PUT /api/v1/organizations/{organization-id}`

- **Header**
```json
{
  "Authorization": "Bearer eyJhbGciOiJIUzI1N...."
}
```

-  **Request Body**
```PUT /api/organization/{organization-id}```
```json
{
  "name": "Team backend",
}
```

### Expected Outcome
1. Successful Update: The endpoint changes the organisation's database profile information and gives a success response if the user is authenticated and submits accurate data.
2. Authentication Errors: The endpoint returns an authentication error if the user is not authenticated or if their session has expired.
3. Validation Errors: The API returns the relevant error messages if the provided data does not pass validation checks (for example, an invalid name format).

- **Successful Response**
On a successful update of the organisation, the API should return a 200 OK status code.
The response body should contain the newly updated organisation details.
```json
{
  "message": "Organisation updated successfully",
  "org": {
    "name": "Team backend",
    "description": "Team backend description"
  }
}
```
- **Authentication Error**
When the current user is not properly authenticated to change the organization detail
```json
{
  "status_code": 401,
  "error": "invalid authentication token",
  "message": "user not authorized for this action",

}
```
- **Invalid Organisation Error**
On invalid error, if the organization is not found with the provided id
```json
{
  "status_code": 404,
  "error": "not found error",
   "message": "organisation not found",
}
```
- **Validation**
If any required field is missing or invalid, the response should return a 400 Bad Request status code with appropriate validation error messages.
```json
{
  "status_code": 400,
  "message": ["name must be a string", "description must be a string"],
  "error": "Bad Request"
}
```
### Purpose
It allows authenticated users to update their organisation information in the application's database. This typically includes fields such as name, description, and other profile-related details.

### Requirements
- Authenticate  and authorize user for the action
- Develop server-side logic to handle organisation profile update.
- Validate user data
- Update fields provided in body
- Ensure compliance with security standards for handling user information.

### Task
- [ ]  Create a PUT endpoint  `PUT /api/v1/organizations/{organization-id}` to update user profile
- [ ]  Implement server-side logic to handle successful and failed update request.
- [ ]  Ensure the user has the proper permissions and authentication to update organisation.
- [ ] Fetch and update the organization details in the database.
- [ ]  Write  tests for updating organisation details.
- [ ]  Perform security testing to ensure data protection and compliance.
- [ ] Update API documentation to reflect the new endpoint and its usage.

### Testing
- Write integration testing end-to-end test for updating organisation data
- Write unit tests for various edge cases and error handling scenarios.
- Perform security testing to ensure data protection and compliance.
- Test various scenarios updating organisation profile

**Comment by markessien** [comment]
this ticket is all over the place. Write it properly
