### ISSUE TITLE
[FEAT] : API endpoint to [GET] subscription cancellation confirmation

### ISSUE THREAD

**Issue by Amal-Salam** [hngprojects/hng_boilerplate_nestjs#168]
## Description
Develop an api endpoint to request for information on the user's cancelled subscription.

## Acceptance Criteria
- [ ] the endpoint should accept HTTP GET requests.
- [ ] the endpoint should be protected and require authentication
- [ ] Confirmation of canceled subscription is being displayed to authenticated user.
- [ ] return appropriate response and status code

### Purpose
    Provides the authenticated user with the details of cancelled subscription.

### Requirements	
- [ ] set up database integration and secure storage
- [ ] ensure compliance with security standards for handling information
- [ ] Retrieve information to the user on cancelled subscription such as:
          - Subscription ID
          - Subscription Plan
          - Cancellation Date

### Parameters:
   subscription_id: string

### Expected Outcome
    successful retrieval of cancelled subscription id, plan and cancellation date.

### Endpoint:
     [GET]/api/v1/user/subscription/{subscription_id}/cancellation/notification

Description
 Get all cancelled subscription information 

 ## Successful Response
    status code:200
       {
           "success": true
              "message": String
        {
          "subscription_id": Int,
             "subscription_plan": String,
                "cancellation_date": DateTime
          }
        }

### Error Response
      status code:500
             {
               "success": false,
               "message": String,
               "status_code":500
              }

### Tasks
- [ ] Create Fetching Logic
- [ ] implement the GET /api/v1/user/subscription/{subscription_id}/cancellation/notification endpoint
- [ ] query database to retrieve subscription details by subscription id and user id
- [ ] Handle errors and return appropriate responses

### Authorization Check
- [ ] Ensure only authorized users(ie users and super admins)can access this point

### Database Operations
- [ ] Create a schema for storing subscription details if not existing
- [ ] securely retrieve details from the database
- [ ] Verify adherence to data protection guidelines.

### Database Schema
      Table Name:  cancelled_Subscription
           id:
                 constraints: string(uuid), unique, primary key ,not null
          plan:
                 constraints: string, not null
          cancelledAt:
                 constraints: string, datetime

### Testing
  Unit Tests
 The systems unit tests should cover
- [ ] Validation of user authorization to view details
- [ ] ensure successful and failed requests are handled appropriately

**Comment by Amal-Salam** [comment]
Team Members working on this issue include:

solomonuche42@gmail.com- Python - Slack_Id - @solomonXuche

**Comment by markessien** [comment]
very unclear ticket and not sure it is needed

**Comment by phurhard** [comment]
Check out #98 
You both working on same thing.

**Comment by Amal-Salam** [comment]
Noted.Thank you.
Will revise.
