### ISSUE TITLE
[FEAT]  Scheduled Blog Post with Time Zone Handling (Admin-Only)

### ISSUE THREAD

**Issue by johnson-oragui** [hngprojects/hng_boilerplate_nestjs#171]
### Description
Implement an API endpoint that allows admins to schedule blog posts, to be published automatically at a specified date and time. This involves creating a scheduling system that moves the content from a scheduled state to a published state at the correct time. Only authenticated admin users should be able to use this endpoint.

### Acceptance Criteria
 - Authentication and Authorization: Only admin users can access the scheduling endpoint.
 - Endpoint Creation: Create an endpoint to schedule blog posts.
 - Scheduled Content Table: Create a table to store scheduled content with fields for title, body, publish date, and status.
 - Publishing Logic: Automatically move scheduled content to the blog table at the specified publish date.
 - Validation: Ensure the publish date is in the future.
 - Background Task: Use a background task to handle the delayed publishing of the content.
 - Error Handling: Proper error messages for unauthorized access, invalid dates, and other potential issues.

### Purpose
To enable admins to schedule blog posts for future publication, ensuring that the content goes live automatically at the specified time and allow for content planning and promotion.

### Requirements
**API Endpoint** (POST /api/v1/blogs/schedule):

 - Permissions:
     - Access restricted to authenticated users with the "admin" role.
     - A Valid token is sent with the Authorization header, the user has to be an admin.
- request header:
     - "Authorization: Bearer omnjHnShbGciOiOumOjFc56..."
- A valid request body
```
{
  "title": "string",  // required if scheduled
  "content" "string",  // required if scheduled
  "genre": "string",  // required if scheduled
  "tags": ["tag1", "tag2", ...],
  "image": "string",  // image url
  "publish_datetime": "2024-07-18T17:00:00Z",  // required if scheduled
  "status": "scheduled" // or draft
}
```
- Validation:
      - Validate publish_datetime to ensure it is in the future and not in the past.
- Successful response:
- status code 201
```
{
  "status_code": 201,
  "message": "Successful",
  "data": {
    "blog_id": String,
    "title": String,
    "content": String,
    "image": "image url",
    "tags": ["tag1", "tag2", ...],
    "author": String,
    "created_at": datetime,
    "publish_datetime": datetime,  // or None if draft
    "status": "scheduled"  //  or None if draft
  }
}
```
- Error Responses:
- Status Code 400
```
{
  "message": "some fields are missing",
  "status": "Un-successful",
  "status_code": 400,
  "error": [object]
 }
```
- Status Code 403
```
{
  "message": String,
  "status": "Un-successful",
  "status_code": 403
}
```

- Status Code 405
```
{
  "message": "Method not allowed",
  "status": "Un-successful",
  "status_code": 405
}
```

- Status Code 500
```
{
  "message": "Internal Server Error",
  "status_code": 500
}
```
- Database Design:
![issues scheduling](https://github.com/user-attachments/assets/6341328c-c865-4aab-b273-c4ba2edb60f9)

## Tasks:
- [ ] Create a model for storing drafts or scheduled content.
- [ ] Implement an authentication system to secure the endpoint.
- [ ] Implement authorization to restrict access to the endpoint to admin users only.
- [ ] Create the API endpoint for scheduling or drafting content.
- [ ] Implement the background task for delayed publishing times (in UTC).
- [ ] Ensure validation for the publish date.
- [ ] Implement logic to handle user-selected time zone and convert it to UTC for the API request.
- [ ] Implement logic within the background job to fetch scheduled content and publish it at the designated time.
- [ ] Update database status to "Published" upon successful blog post publication.
- [x] Add error handling for common issues (e.g., unauthorized access, invalid date).

## Admins should be able to:

 - Schedule blog posts for automatic publishing at a designated date and time.
 - Easily select the publish time in their familiar local time zone.
 - Benefit from consistent and reliable blog delivery without manual intervention.
 - Appropriate error messages are returned for unauthorized access and invalid input.
