### ISSUE TITLE
[FEAT]: API endpoint to Remove a User from an Organization - Backend

### ISSUE THREAD

**Issue by olakadasami** [hngprojects/hng_boilerplate_nestjs#173]
## Description
Develop an API endpoint that removes a user from an organization.

### Authentication Middleware
- Implement middleware to ensure the user (org admin) is authenticated using JWT.
- If authentication fails, return a 401 Unauthorized status code.
- If authenticated, proceed with the request.

### Authorization
- Implement an authorization check to ensure that only the organization's owner (org admin) has the ability to remove users.

### API Endpoint Implementation:
- The endpoint should be accessible at `/api/v1/organizations/{orgId}/users/{userId}`.
- The endpoint should accept http DELETE request.

### Remove User from Organization:
- Upon successful validation, the API should remove the user to the specified organization.

### Response:
- On success, the API should return a `204 No Content` status code with the success message.
- On failure, the API should return a 400 Bad Request status code with appropriate error messages.

## Successful Response
```css
HTTP/1.1 204 No Content

```

## Unsuccessful Response
```json
{
  "status": "Bad Request",
  "message": "Client error",
  "status_code": 400
}
```

## Unauthenticated Error Message
```json
{
  "status": "Unauthorized",
  "message": "User not authenticated",
  "status_code": 401
}
```

## Unauthorized Error Message
```json
{
  "status": "Forbidden",
  "message": "Only owners can add users",
  "status_code": 403
}
```

## Purpose
Provide a backend service that allows organizations' owners to remove users from organizations, ensuring proper authentication, authorization, and validation.

## Requirements
- Implement middleware for JWT authentication.
- Implement an authorization check to ensure that only the organization's owner has the ability to remove users.
- Develop server-side logic to remove a user from an existing organization.

## Expected Outcome
The API endpoint allows users (organization owners) remove users(members) from their organization with appropriate authentication and authorization

## Task 
- [ ] Create the endpoint HTTP DELETE `/api/v1/organizations/{orgId}/users/{userId}` to remove a user from an organization.
- [ ] Implement authentication middleware to validate JWT tokens.
- [ ] Implement an authorization check to ensure that only the organization's owner has the ability to add users.
- [ ] Validate the request param {orgId} and {userId}
- [ ] Write unit tests for all scenarios, including successful removal of user from organization, validation errors, and authentication/authorization checks.
- [ ] Perform security testing to ensure data protection and compliance.

## Testing
- Write unit tests for successful removal of organization members.
- Write unit tests for fields validation.
- Write unit tests for bad client requests.
- Write unit tests for authentication and authorization checks.
- Perform security testing to ensure data protection and compliance.

**Comment by markessien** [comment]
you cannot just add users, you have to invite them

**Comment by olakadasami** [comment]
@markessien I've made changes as adding users through invitation is already taken
