### ISSUE TITLE
[FEAT]: OS-003: Disable Role API

### ISSUE THREAD

**Issue by PearlPerfect** [hngprojects/hng_boilerplate_nestjs#176]
###  **Description**:
Implement an endpoint to disable roles. This endpoint will allow the admin to disable roles within an organization.

### **1.  Endpoint Creation:**

- Create an API endpoint to allow admins to disable roles within their organization.
- Ensure that the admins and Super Admins are authenticated and authorized before they can access this endpoint.
- Ensure that the ID of the role to be disabled is passed as a parameter
- Ensure all the users on the disabled role are added to the organisation's defaule role

### **2. Database Schema Update:**

- Update the database schema to exclude disabled roles.
- Update database schema to change all the users on the disabled role to the default role.

### **3. Success and Error Handling:**

- Handle success and error responses appropriately.
### **4. Testing and Debugging:**

- Write unit tests for the role deactivation endpoint.
- Perform integration testing to ensure the endpoint works as expected.
- Debug any issues that arise during testing.

###  **Purpose**
To provide an endpoint for admins to disable any role within their organization, ensuring only authorized users can perform this action and maintaining system security.

### **1. Endpoint Creation:**

- Implement the endpoint PUT /api/v1/:{roleId}/disable to handle role creation.
- Validate roleID passed by the user on the server side.
- Ensure only authenticated and authorized admins can access this endpoint.

### **2. Database Schema Update:**

- Modify the database schema to exclude the disabled role table or update the existing table to include organization references and users new role.

### **3. Success and Error Handling:**

- Return appropriate success messages when a role is disableded successfully.
- Return error messages when there is problem while trying to disable a role, include appropriate status codes.

### **4.  Security Measures:**

- Use HTTPS for secure data transmission.
- Validate role Id provided on the server side.
- Encrypt sensitive data where necessary.

### **5. Expected Outcome:**
Endpoint to allow admin disable roles

### **Tasks:**

- [ ] Create an endpoint (PUT /api/v1/:{roleId}/disable/) to handle disabling a role.
- [ ] Validate role Id provided on the server side.
- [ ] Update the database schema to exclude disabled roles.
- [ ] Update database schema to update uses whose roles have been deactivated to the default organization role
- [ ] Implement server-side logic to handle successful and failed role creation attempts.
- [ ] Ensure all sensitive data is encrypted and secure.
- [ ] Implement logging for errors and transaction attempts.
- [ ] Write unit tests for the role disabling endpoint.
- [ ] Write integration tests for the role creation process.

### **Testing:**

- [ ] Write unit tests for backend validation and transaction handling.
- [ ] Write integration tests for the end-to-end role disabling process.
- [ ] Perform security testing to ensure data protection and compliance.
- [ ] Test all instances for disabling a role (e.g., successful, failed, retry).

### **request body**
`{
  "role_id": "String",
  "organization_id": "String",
  "permissions": [
    "String"
  ]
}`

### **Response Body (Success)**
`{
"status_code": 200,
  "message": "Role disabled successfully."
}`

### **Response Body (Error)**
`{
  "message": "Unable to disble role.",
  "status_code": 400
}`

**Comment by markessien** [comment]
what happens to users on that role when it is disabled?

**Comment by PearlPerfect** [comment]
> what happens to users on that role when it is disabled?

The users on the role that is disabled will change to a more generic role, say the default role

**Comment by PearlPerfect** [comment]
Will be reopened soon
