### ISSUE TITLE
[FEAT]  Implement Notification Page API

### ISSUE THREAD

**Issue by Samilincoln** [hngprojects/hng_boilerplate_nestjs#179]
## Description
 Creating a visually appealing and user-friendly notification page that displays notifications in an organized manner following the Figma design

## Acceptance Criteria
1. **Layout Implementation**
   - The notification page should match the Figma design.
   - The layout should be responsive and work across different screen sizes.
   
2. **Unread and Read Pages**
   - There should be distinct pages for unread and read notifications.
   - Users should be able to switch between unread and read notifications seamlessly.

3. **Notification Cards**
   - Notification cards should display title, message preview, and timestamp.
   - Users should be able to mark notifications as read/unread from the card.

4. **Filtering and Sorting**
   - Users should be able to filter notifications by type and date.
   - Users should be able to sort notifications by newest or oldest first.

### Purpose
The purpose of this project is to enhance the user experience by providing a clear and organized way to view and manage notifications.

### Requirements
1. **Design Layout for Notification Page**
   - Create a responsive layout based on the Figma design.
   - Ensure compatibility across various screen sizes.

2. **Unread and Read Notifications Pages**
   - Implement separate pages for unread and read notifications.
   - Navigate between these pages seamlessly.

3. **Notification Cards**
   - Design notification cards displaying title, message preview, and timestamp.
   - Include options to mark notifications as read/unread.

4. **Filtering and Sorting**
   - Add filtering options (e.g., by type, date).
   - Implement sorting functionality (e.g., newest first, oldest first).	

### Expected Outcome
Users should be able to view notifications on a well-designed notification page with clear separation between unread and read notifications. They should also have the ability to filter and sort notifications as needed.

## API Endpoints
- **GET /api/v1/notifications**: Fetch all notifications.

**Request**
```JSON
{
    "method": "GET",
    "url": "/api/v1/notifications",
    "headers": {
        "Authorization": "Bearer <token>"
    }
}
```

**Response body (success)**
```JSON
[
    {
        "id": "1",
        "title": "Welcome",
        "message": "Welcome to our service!",
        "timestamp": "2024-07-17T12:00:00Z",
        "read": false,
        "type": "general"
    },
    {
        "id": "2",
        "title": "Update Available",
        "message": "A new update is available.",
        "timestamp": "2024-07-16T12:00:00Z",
        "read": true,
        "type": "update"
    }
]
```

**Response body (error)**
```JSON
{
    "error": "Unauthorized",
    "message": "Authentication token is missing or invalid."
}
```

- **GET /api/v1/notifications/unread**: Fetch unread notifications.

**Request**
```JSON
{
    "method": "GET",
    "url": "/api/v1/notifications/unread",
    "headers": {
        "Authorization": "Bearer <token>"
    }
}
```

**Response body (success)**
```JSON
[
    {
        "id": "1",
        "title": "Welcome",
        "message": "Welcome to our service!",
        "timestamp": "2024-07-17T12:00:00Z",
        "read": false,
        "type": "general"
    }
]
```

**Response body (error)**
```JSON
{
    "error": "Unauthorized",
    "message": "Authentication token is missing or invalid."
}
```

- **GET /api/v1/notifications/read**: Fetch read notifications.
**Request**
```JSON
{
    "method": "GET",
    "url": "/api/v1/notifications/read",
    "headers": {
        "Authorization": "Bearer <token>"
    }
}
```

**Response body (success)**
```JSON
[
    {
        "id": "2",
        "title": "Update Available",
        "message": "A new update is available.",
        "timestamp": "2024-07-16T12:00:00Z",
        "read": true,
        "type": "update"
    }
]
```

**Response body (error)**
```JSON
{
    "error": "Unauthorized",
    "message": "Authentication token is missing or invalid."
}
```

- **PATCH /api/v1/notifications/:id/mark-read**: Mark a notification as read.
**Request**
```JSON
{
    "method": "PATCH",
    "url": "/api/v1/notifications/1/mark-read",
    "headers": {
        "Authorization": "Bearer <token>",
        "Content-Type": "application/json"
    },
    "body": {
        "read": true
    }
}
```

**Response body (success)**
```JSON
{
    "id": "1",
    "title": "Welcome",
    "message": "Welcome to our service!",
    "timestamp": "2024-07-17T12:00:00Z",
    "read": true,
    "type": "general"
}
```

**Response body (error)**
```JSON
{
    "error": "Not Found",
    "message": "Notification with the given ID not found."
}
```

- **PATCH /api/v1/notifications/:id/mark-unread**: Mark a notification as unread.
**Request**
```JSON
{
    "method": "PATCH",
    "url": "/api/v1/notifications/2/mark-unread",
    "headers": {
        "Authorization": "Bearer <token>",
        "Content-Type": "application/json"
    },
    "body": {
        "read": false
    }
}
```

**Response body (success)**
```JSON
{
    "id": "2",
    "title": "Update Available",
    "message": "A new update is available.",
    "timestamp": "2024-07-16T12:00:00Z",
    "read": false,
    "type": "update"
}
```

**Response body (error)**
```JSON
{
    "error": "Not Found",
    "message": "Notification with the given ID not found."
}
```

- **GET /api/v1/notifications/filter**: Filter notifications by type or date.
**Request**
```JSON
{
    "method": "GET",
    "url": "/api/v1/notifications/filter",
    "headers": {
        "Authorization": "Bearer <token>"
    },
    "params": {
        "type": "general",
        "date": "2024-07-17"
    }
}
```

**Response body (success)**
```JSON
[
    {
        "id": "1",
        "title": "Welcome",
        "message": "Welcome to our service!",
        "timestamp": "2024-07-17T12:00:00Z",
        "read": false,
        "type": "general"
    }
]
```

**Response body (error)**
```JSON
{
    "error": "Bad Request",
    "message": "Invalid filter parameters provided."
}
```

- **GET /api/v1/notifications/sort**: Sort notifications by date.
**Request**
```JSON
{
    "method": "GET",
    "url": "/api/v1/notifications/sort",
    "headers": {
        "Authorization": "Bearer <token>"
    },
    "params": {
        "order": "newest"
    }
}
```

**Response body (success)**
```JSON
[
    {
        "id": "1",
        "title": "Welcome",
        "message": "Welcome to our service!",
        "timestamp": "2024-07-17T12:00:00Z",
        "read": false,
        "type": "general"
    },
    {
        "id": "2",
        "title": "Update Available",
        "message": "A new update is available.",
        "timestamp": "2024-07-16T12:00:00Z",
        "read": true,
        "type": "update"
    }
]
```

**Response body (error)**
```JSON
{
    "error": "Bad Request",
    "message": "Invalid sort parameters provided."
}
```

### Tasks
- [ ] Create API endpoints to fetch notifications.
- [ ] Implement endpoints to mark notifications as read/unread
- [ ] Provide endpoints for filtering and sorting notifications.

### Testing
1. **Test GET /api/v1/notifications**
- [ ] Test with valid and invalid tokens.
- [ ] Ensure all notifications are fetched correctly.

2. **Test GET /api/v1/notifications/unread**
- [ ] Test with valid and invalid tokens.
- [ ] Ensure unread notifications are fetched correctly.

3. **Test GET /api/v1/notifications/read**
- [ ] Test with valid and invalid tokens.
- [ ] Ensure read notifications are fetched correctly.

4. **Test PATCH /api/v1/notifications/:id/mark-read**
- [ ] Test marking a valid notification as read.
- [ ] Test with an invalid notification ID.
- [ ] Test with valid and invalid tokens.

5. **Test PATCH /api/v1/notifications/:id/mark-unread**
- [ ] Test marking a valid notification as unread.
- [ ] Test with an invalid notification ID.
- [ ] Test with valid and invalid tokens.

6. **Test GET /api/v1/notifications/filter**
- [ ] Test filtering by type.
- [ ] Test filtering by date.
- [ ] Test with valid and invalid tokens.

7. **Test GET /api/v1/notifications/sort**
- [ ] Test sorting by newest.
- [ ] Test sorting by oldest.
- [ ] Test with valid and invalid tokens.

**Comment by markessien** [comment]
this is a frontend ticket and duplicate of other backend tickets
