### ISSUE TITLE
[FEAT]: Single Products API

### ISSUE THREAD

**Issue by JoshuaOloton** [hngprojects/hng_boilerplate_nestjs#181]
## Description
- Develop API endpoint that retrieves information about a single product. The response includes product details such as ID, name, description, price, and availability.

## Acceptance Criteria
- The endpoint `/api/v1/products/{product-id}` is accessible via a GET request.
- When a valid `product-id` is provided, the endpoint returns a 200 OK status.
- When an invalid `product-id` format is provided, the endpoint returns a 400 Bad Request status.
- On an invalid request, the response body contains an error message indicating the invalid product ID format.
- When a `product-id` that does not exist is provided, the endpoint returns a 404 Not Found status.
- For a product that does not exist, the response body contains an error message indicating that the product was not found.
- If an unexpected server error occurs, the endpoint returns a 500 Internal Server Error status.
- The response body of an error 500 response contains an error message indicating that an unexpected error occurred.
- Ensure that all unit and integration tests for the fetch single product endpoint are comprehensive, and verify the functionality correctly.

### Purpose
- This provides a backend service that allows fetching detailed information on selected/specific product

### Requirements	

- [ ] Implement an endpoint to view single product
- [ ] Return detailed information on products
- [ ] Handle situations where products don't exist

### Expected Outcome
- API endpoint that returns detailed information on specific product

### Tasks

- [ ] Create an endpoint `/api/v1/products/{product-id}` to fetch details of a single product.
- [ ] Implement server-side logic to handle successful and failed product retrieval requests.
- [ ] Ensure all sensitive data is encrypted and secure.
- [ ] Implement logging for errors and product retrieval attempts.
- [ ] Write unit tests for the fetch single product endpoint.
- [ ] Write integration tests for the fetch single product logic.
- [ ] Perform security testing to ensure data protection and compliance.

## Database Schema
```
Table products {
  id int [pk, increment]
  name varchar(255) [not null]
  description text
  price decimal(10,2) [not null]
  available boolean [default: true]
  category varchar(255)
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
}
```

### Success Response
 - #### Code: 200 OK
 - #### Content:

```
{
  "product": {
    "id": "string",
    "name": "string",
    "description": "string",
    "price": "number",
    "available": "boolean",
    "category": "string",
    "created_at": "string",
    "updated_at": "string"
  }
}
```

### Error Responses
- #### Code: 400 BAD REQUEST
- #### Content:

```
{
  "error": "Invalid product ID"
}
```

- #### Code: 404 NOT FOUND
- #### Content:

```
{
  "error": "Product not found"
}
```

- #### Code 422: UNPROCESSABLE CONTENT / VALIDATION ERROR
#### Content:

```
{
  "errors": {
    "field": "<field>",
    "message": "<message>"
  }
}
```

- #### Code: 500 INTERNAL SERVER ERROR
- #### Content:

```
{
  "error": "An unexpected error occurred"
}
```

### Fetch Single Product By ID
`curl -X GET "https:/<base-url>/api/v1/products/12345`

**Comment by davieoba** [comment]
| **Slack_id**   | **github**      | **stack**             | **role**   |
|----------------|-----------------|-----------------------|------------|
| @JoshuaOloton  | @JoshuaOloton   | python (FastAPI)      | Team Lead  |
| @Leona         | @Leona-cloud          | nestjs                | Member     |
| @Dave-backend  | @davieoba       | java (Spring Boot)    | Member     |
