### ISSUE TITLE
[FEAT] View User Profile that belong to same Organization - BACKEND

### ISSUE THREAD

**Issue by aniebietafia** [hngprojects/hng_boilerplate_nestjs#186]
## Description

Users that belong to the same organization can view each others profile but a user that does not belong to the same organization cannot view the profile of another user.

## Acceptance Criteria

- The endpoint should be accessible at `GET /api/v1/users/:id`
- User should be authenticated to access the endpoint.
- The endpoint should return a `404` status code if the user does not exist.
- The endpoint should return a `403` status code if the user is not in the same organization.
- The endpoint should return a `200` status code if the user is in the same organization.
- The endpoint should return the user's profile if the user is in the same organization.

### Purpose

Be able to view the profile of a user that belongs to the same organization.

### Requirements

- The user should be able to view the profile of another user that belongs to the same organization.
- The user should not be able to view the profile of another user that does not belong to the same organization.
- Create a Table to connect users Table to organizations Table.
- Develop API endpoint to view the profile of a user.

### Database Schema [UserOrganisation Table]

```sql
CREATE TABLE user_organisation (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id),
  organisation_id INT REFERENCES organisations(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
```

### API Endpoint

```http
GET /api/v1/users/:id
```

#### Request body

```json
{
  "id": 1
}
```

#### Response

```json
{
  "id": 1,
  "first_name": "John",
  "last_name": "Doe",
  "email": "johnny@test.com",
  "role": "admin",
  "organisations": [
    {
      "id": 1,
      "name": "Andela",
      "description": "A software company"
    },
    {
      "id": 2,
      "name": "Facebook",
      "description": "A social media company"
    }
  ]
}
```

#### Error Responses

```json
{
  "status": 404,
  "error": "User not found"
}
```

```json
{
  "status": 403,
  "error": "User not in the same organization"
}
```

### Expected Outcome

User should be able to view the profile of another user that belongs to the same organization.

### Tasks

- [ ] Create a Table to connect users Table to organizations Table.
- [ ] Develop API endpoint to view the profile of a user.
- [ ] Write tests for the API endpoint.

### Testing

- Unit tests should be written for the API endpoint.
- Integration tests should be written for the API endpoint.

**Comment by markessien** [comment]
duplicate
