### ISSUE TITLE
[FEAT] Implement API to Get all Blog Posts of a Particular  Author (Superadmin) 

### ISSUE THREAD

**Issue by DavidIfebueme** [hngprojects/hng_boilerplate_nestjs#190]
## Description

Creating an API that allows authenticated superadmins to retrieve all blog posts authored by any superadmin, providing easy access to their content. 

### Background:
Superadmin is a user with the superadmin role on the database via role based access control

### Purpose

To enable superadmins to view all blog posts written by any specific superadmin, ensuring they can manage and review content efficiently while implementing robust security measures.

### Requirements	

- [ ] Develop a secure RESTful API endpoint (`GET /api/v1/users/:user_id/blog-posts`) to handle requests for retrieving blog posts by a specific superadmin.
- [ ] Ensure server-side validation and sanitization of user input to prevent security vulnerabilities.
- [ ] Implement logging mechanisms to track API requests and responses for auditing and debugging purposes.
- [ ] Authenticate requests using the superadmin token in the authorization header.
- [ ] Implement access control to ensure only superadmins (users with the superadmin role) can access this endpoint.

### Fetch Superadmin Blogs:

- Description: Provides a list of blog posts written by the specified superadmin.

- Endpoint: `GET /api/v1/users/:user_id/blog-posts`

- Headers: `Authorization: Bearer <superadmin_token>`

### Request Parameters
- `user_id`: String (required) - The ID of the user with superadmin role whose blog posts are to be retrieved.

## Successful Response
```
{
  "current_page": Int,
  "total_pages": Int,
  "total_results": Int,
  "blogs": [
    {
      "id": "String",
      "title": "String",
      "content": "String",
      "created_date": "String",
      "tags": ["tag1", "tag2"]
    },
    {
      "id": "String",
      "title": "String",
      "content": "String",
      "created_date": "String",
      "tags": ["tag3", "tag4"]
    }
  ]
}
```
## Error Responses

```
{
  "message": "Superadmin not found",
  "error": "Not Found",
  "status_code": 404
}
```

```
{
  "message": "You're not superadmin",
  "error": "Access Denied",
  "status_code": 401
}
```

## Tasks

- [ ] Develop a secure `GET endpoint/api/v1/users/:user_id/blog-posts` to fetch blog posts by a specific superadmin.

- [ ] Ensure server-side validation and sanitization of user input to prevent security vulnerabilities.

- [ ] Configure logging to capture API activities and errors for monitoring and troubleshooting.

- [ ] Authenticate requests using the superadmin token.

- [ ] Implement access control to ensure only authenticated superadmins can access this endpoint.

- [ ] Implement pagination logic if needed to handle multiple posts and return paginated results.

## Testing

- Write comprehensive unit tests to validate backend logic, including input validation and response formatting.

- Conduct integration tests to verify endpoint functionality and interaction with database queries.

- Perform security testing to identify and address potential vulnerabilities, ensuring robust data protection measures.

**Comment by markessien** [comment]
we do not have superadmin routes

**Comment by DavidIfebueme** [comment]
@markessien edited out the superadmin route to a /user endpoint which should only be accessed by properly authenticated superadmins

**Comment by markessien** [comment]
this does not make sense. last try then I close the ticket

**Comment by phurhard** [comment]
Await marks first approval

**Comment by DavidIfebueme** [comment]
@markessien To clarify, the purpose of this endpoint `GET /api/v1/users/:userId/blog-posts` is to let auth superadmins to review all blog posts made by other superadmins, as you mentioned here(#46) that only superadmins should be allowed to create blog posts. 

This issue builds on this issue on rbac(#153) that has already gotten first approval.

**Comment by nedssoft** [comment]
Even if Mark approves this ticket, it still won't pass second approval because it does not follow the accepted conventions, despite how much we have stressed the importance of this

**Comment by DavidIfebueme** [comment]
@nedssoft, I've edited the payloads and responses to be in snake case

**Comment by markessien** [comment]
this ticket is closed, as it has not been properly thought through, despite multiple feedback. Do not re-open it again with the same topic
