### ISSUE TITLE
[FEAT] Delete Job Listings by an Admin

### ISSUE THREAD

**Issue by githukueliud** [hngprojects/hng_boilerplate_nestjs#192]
### Description

 - Create an API endpoint that allows admins to delete a job listing after proper security measures.

 ### Acceptance Criteria
 - The endpoint should be accessible at DELETE /api/v1/job-listings/:jobId.
 - The endpoint should accept HTTP DELETE requests.
 - The endpoint should be secured to ensure that only authenticated admins can delete a job listing.
 - Requests to the endpoint must include a valid authentication token in the Authorization header. Authorization: Bearer <token>

### Request body

```
{

}
```

### Response
 - On a successful deletion of the job listing, the API should return a 200 Ok status code.
 - The response body should contain status and a message

```
{
  "status": "success",
  "message": "Job listing deleted successfully"
}
```

###  Validation

 - If the user is not authorized as an admin, the API should return a 400 Bad Request status code with appropriate validation error messages.

```
{
  "status": "unsuccessful",
  "message": "Unable to perform the request"
 }
```

 - If the job listing does not exist, the API should return a 404 Not Found status code with appropriate validation error messages.

```
{
  "status": "unsuccessful",
  "message": "Unable to perform the request"
 }
```

### Purpose
 - Provides a secure backend service that allows admins to delete job listings.

### Requirements
 - Develop server-side logic for admins to delete job listings.
 - Securely handle job listings deletion and comply with security standards.

### Expected Outcome

 - API endpoint allows users to update passwords with appropriate validation and security measures.

### Tasks

  - [ ] Define the server-side application's DELETE /api/v1/admin/job-listings/:jobId route.
  -  [ ] Ensure requests include a valid token in the Authorization header.
  - [ ] Validate that user is an admin.
  - [ ] Ensure that the job listing exists.

### Testing

 - Write unit tests to validate user is logged in and that the user has admin level authority.
 - Write integration tests to ensure end-to-end functionality.

**Comment by markessien** [comment]
we do not have admin specific routes
