### ISSUE TITLE
[FEAT] Endpoints for CRUD of images

### ISSUE THREAD

**Issue by Samilincoln** [hngprojects/hng_boilerplate_nestjs#204]
## Description
 Creating a set of API endpoints for managing images, including creating, reading, updating, and deleting images.

## Acceptance Criteria
1. **Create Image**
   - New images can be uploaded with a URL and description.
   - The new image details are returned upon successful creation.
   - Error handling for invalid image data.

2. **Read Images**
   - Users can fetch a list of all images.
   - Users can fetch a specific image by its ID.
   - Appropriate error messages for not found or unauthorized requests.

3. **Update Image**
   - Users can update the description of an existing image.
   - The updated image details are returned upon successful update.
   - Error handling for invalid updates.

4. **Delete Image**
   - Users can delete an image by its ID.
   - A success message is returned upon successful deletion.
   - Error handling for invalid delete requests.

### Purpose
The purpose of this project is to allow users to manage images through a well-defined API.

### Requirements
1. **Create Image**
   - Upload a new image with a URL and description.

2. **Read Images**
   - Fetch all images or a specific image by ID.

3. **Update Image**
   - Update the description of an existing image.

4. **Delete Image**
   - Remove an image by ID.

### Expected Outcome
Users should be able to manage images through a secure API, performing CRUD operations with appropriate responses.

## API Endpoints
- **GET /v1/api/images**: Fetch all images.

**Request**
```JSON
{
    "method": "GET",
    "url": "/v1/api/images",
    "headers": {
        "Authorization": "Bearer <token>"
    }
}
```

**Response body (success)**
```JSON
[
    {
        "id": "1",
        "url": "https://example.com/image1.jpg",
        "description": "Sample image 1",
        "timestamp": "2024-07-17T12:00:00Z"
    },
    {
        "id": "2",
        "url": "https://example.com/image2.jpg",
        "description": "Sample image 2",
        "timestamp": "2024-07-16T12:00:00Z"
    }
]

```

**Response body (error)**
```JSON
{
    "error": "Unauthorized",
    "message": "Authentication token is missing or invalid."
}
```

- **GET /api/v1/images/:id**: Fetch specific image by id.

**Request**
```JSON
{
    "method": "GET",
    "url": "/api/v1/images/1",
    "headers": {
        "Authorization": "Bearer <token>"
    }
}
```

**Response body (success)**
```JSON
{
    "id": "1",
    "url": "https://example.com/image1.jpg",
    "description": "Sample image 1",
    "timestamp": "2024-07-17T12:00:00Z"
}

```

**Response body (error)**
```JSON
{
    "error": "Not Found",
    "message": "Image with the given ID not found."
}

```

- **POST /api/v1/images**: Upload a new image.
**Request**
```JSON
{
    "method": "POST",
    "url": "/api/v1/images",
    "headers": {
        "Authorization": "Bearer <token>",
        "Content-Type": "application/json"
    },
    "body": {
        "url": "https://example.com/newimage.jpg",
        "description": "New sample image"
    }
}

```

**Response body (success)**
```JSON
{
    "id": "3",
    "url": "https://example.com/newimage.jpg",
    "description": "New sample image",
    "timestamp": "2024-07-17T13:00:00Z"
}

```

**Response body (error)**
```JSON
{
    "error": "Bad Request",
    "message": "Invalid image data provided."
}

```

- **PATCH /api/v1/images/:id**: Update an existing image details.
**Request**
```JSON
{
    "method": "PATCH",
    "url": "/api/v1/images/1",
    "headers": {
        "Authorization": "Bearer <token>",
        "Content-Type": "application/json"
    },
    "body": {
        "description": "Updated sample image 1"
    }
}

```

**Response body (success)**
```JSON
{
    "id": "1",
    "url": "https://example.com/image1.jpg",
    "description": "Updated sample image 1",
    "timestamp": "2024-07-17T12:00:00Z"
}

```

**Response body (error)**
```JSON
{
    "error": "Not Found",
    "message": "Image with the given ID not found."
}
```

- **DELETE /api/v1/images/:id**: Delete an image by id.
**Request**
```JSON
{
    "method": "DELETE",
    "url": "/api/v1/images/1",
    "headers": {
        "Authorization": "Bearer <token>"
    }
}
```

**Response body (success)**
```JSON
{
    "message": "Image deleted successfully."
}
```

**Response body (error)**
```JSON
{
    "error": "Not Found",
    "message": "Image with the given ID not found."
}
```

### Tasks
- [ ] Create API endpoints to fetch all images.
- [ ] Create API endpoints to fetch an image by id.
- [ ] Create API endpoints to upload a new image.
- [ ] Create API endpoints to update an existing image.
- [ ] Create API endpoints to delete an image by ID.

### Testing
1. **Test GET /v1/api/images**
- [ ] Test with valid and invalid tokens.
- [ ] Test fetching all images with a valid token.
- [ ]  Test unauthorized access without a token.

2. **Test GET /v1/api/images/**
- [ ] Test fetching an image with a valid ID and token.
- [ ] Test fetching an image with an invalid ID.
- [ ] Test unauthorized access without a token.

3. **Test POST /v1/api/images**
- [ ] Test uploading a new image with valid data and token.
- [ ] Test uploading a new image with missing or invalid data.
- [ ] Test unauthorized access without a token.

4. **Test PATCH /v1/api/images/**
- [ ] Test updating an image with a valid ID, description, and token.
- [ ] Test updating an image with an invalid ID.
- [ ] Test unauthorized access without a token.

5. **Test DELETE /v1/api/images/**
- [ ] Test deleting an image with a valid ID and token.
- [ ] Test deleting an image with an invalid ID.
- [ ] Test unauthorized access without a token.

**Comment by ugberaeseac** [comment]
This is multiple tickets... You can only work on one ticket.

**Comment by Samilincoln** [comment]
Thanks 
Corrected

**Comment by Samilincoln** [comment]
> This is multiple tickets... You can only work on one ticket.

correction has been made
Please review

**Comment by markessien** [comment]
You cannot retrieve ALL images. You can retrieve an image by specifying its slug

**Comment by Samilincoln** [comment]
> You cannot retrieve ALL images. You can retrieve an image by specifying its slug

correction has been made.
