### ISSUE TITLE
[FEAT]: Fetch Single Team by ID Endpoint

### ISSUE THREAD

**Issue by bruce-pain** [hngprojects/hng_boilerplate_nestjs#207]
## Description

Create an endpoint to retrieve details for a single team to which the user belongs.

## Acceptance Criteria

**Endpoint implementation**:

- The endpoint should be accessible at `/api/v1/teams/{:teamId}`

- The endpoint should only accept HTTP `GET` requests

**Endpoint security**:

- Only authenticated users can have access to the endpoint

- A user must have the appropriate permissions to access the endpoint

- Each request to the endpoint must include a valid authentication token in the Authorization header

- `Authorization: Bearer <token>`

**Validation**

- The endpoint should check whether the provided `teamId` is valid, that is, the `teamId` exists in the database.

- If the validation succeeds (team exists):

- send a response with team details retrieved from the database with an HTTP status code of `200` (OK)

- If the validation fails (the team does not exist):

- send an error response with HTTP status code of `404` (Not Found)

### Sample Request

Route: `GET` `/api/v1/teams/{:teamId}`

- Query parameters:

- `teamId`: UUID string

### Accessing Protected Routes

**Authorization Header**

- Given a valid token in the Authorization header, the system should allow access and return the requested data when the user accesses a protected route.

```json
{
  "Authorization": "Bearer <token>"
}
```

- When a request is given without an authorization header or with an invalid token when the user accesses a protected route, the system should return 401 Unauthorized status.

### Sample Response

- **successful response**

`teamId` is valid and team details have successfully been retrieved from the database

```json
{
  "status": "success",
  "message": "Team details retrieved successfully",
  "data": {
    "id": "d2ccacfa-666c-4ef3-beb2-fdc292ba2711",
    "name": "Team Dynamo",
    "description": "Maximum composure",
    "created_at": "timestamp",
    "updated_at": "timestamp"
  },
  "status_code": 200
}
```

- **unsuccessful response**

  - `teamId` is invalid and team details cannot be retrieved from the database

  ```json
  {
    "status": "error",
    "message": "Team with this ID cannot be found",
    "status_code": 404
  }
  ```

  - The user is unauthenticated and cannot access the endpoint

  ```json
  {
    "status": "error",
    "message": "Access denied, Unauthorized request",
    "status_code": 401
  }
  ```

### Purpose

The endpoint provides necessary data about a single team's details for the frontend

### Requirements

- [ ] Ensure the endpoint is being accessed by an authenticated user

- [ ] Ensure that users can only fetch team details for teams they belong in

- [ ] Develop server-side logic to fetch team details by ID

- [ ] Ensure that data retrieval complies with security standards

### Expected Outcome

A secured API endpoint that fetches team details by ID from the backend, to support the team details page frontend

### Tasks

- [ ] Implement the endpoint route `/api/v1/teams/{:teamId}`
- [ ] Query the database to retrieve team by team ID
- [ ] Ensure that only authorized users can access the endpoint
- [ ] Implement error handling for scenarios when the user is unauthorized and when the team cannot be found, with the appropriate HTTP status codes
- [ ] Return a response body in the format specified above, with the `200` (OK), HTTP status code.

### Testing

- Unit testing for the API endpoint, covering authentication logic, retrieval, error handling etc
- Integration testing to ensure end-to-end functionality.
- Security testing for data protection (e.g users can only see team details for teams they belong in)

**Comment by markessien** [comment]
we do not have any concept like teams in this app
