### ISSUE TITLE
[FEAT] Multi Device Login Support

### ISSUE THREAD

**Issue by JohnKamaujk** [hngprojects/hng_boilerplate_nestjs#211]
### **Description:**
Allow users to log in from multiple devices simultaneously and maintain session continuity.

### **Acceptance Criteria:**

1. **Multiple Active Device Login Sessions:**
   - Users can log in from multiple devices at the same time. Each device has a unique session ID.

2. **Track New Devices:**
   - New devices are recorded and managed. Device information is collected server-side and stored in the session table, including `(device_browser, device_browser_version, device_os, device_os_version, device_type, device_brand, device_model)`.

3. **Session Continuity:**
   - Recognize and maintain sessions for previously logged-in devices.

### **Tasks:**

- [ ] **Endpoint Implementation:** Create a POST endpoint `/api/v1/auth/login` for multi-device logins.
- [ ] **Session Management:** Implement logic to track and manage sessions independently for each device.
- [ ] **Token Generation and Expiry:** Develop JWT token generation with 1-hour expiry and handle token expiration.
- [ ] **Authorization Mechanism:** Implement middleware to validate JWT tokens for protected route access.
- [ ] **Error Handling and Response:** Define and implement error handling for login failures and token validation.
- [ ] **Testing:** Create unit tests for login functionality, session management, token handling, and error responses.
- [ ] **Documentation:** Update API documentation for `/api/v1/auth/login` endpoint, payloads, responses, and error codes.
- [ ] **Integration and Deployment:** Integrate feature, deploy in development environment, and document deployment procedures.

### **Endpoint Information:**

**POST /api/v1/auth/login**

### **Request and Response Examples:**

**Login Request:**

```json
{
  "email": "user@example.com",
  "password": "securepassword"
}
```

**Login Response (200 OK):**

```json
{
  "status_code": 200,
  "status": "success",
  "message": "Login succesfull",
  "data": 
     "user": {
        "id": "user123",
        "name": "John Doe",
        "email": "user@example.com",
        "key":"value // other key value pairs like organisations etc",
        "last_login_device": {
            "device_browser": "Chrome",
            "device_browser_version": "91.0",
            "device_os": "iOS",
            "device_os_version": "14.6",
            "device_type": "mobile",
            "device_brand": "Apple",
            "device_model": "iPhone 12"
       }
     },
    "session_id": "abcdef123456",
    "access_token": "eyJhbGciOiJIUzI1N...."
}
```

**Error Response (400 Bad Request):**

```json
{
  "status_code": 400,
  "error": "Invalid credentials",
  "message": "The email or password provided is incorrect."
}
```

**Error Response (500 Internal Server Error):**

```json
{  
  "status_code": 500
  "error": "Server error",
  "message": "An unexpected error occurred. Please try again later."
}
```

### **Database Schema:**

```sql
CREATE TABLE sessions (
  session_id UUID PRIMARY KEY,
  user_id UUID NOT NULL,
  device_browser TEXT,
  device_browser_version TEXT,
  device_os TEXT,
  device_os_version TEXT,
  device_type TEXT,
  device_brand TEXT,
  device_model TEXT,
  expires_at TIMESTAMP NOT NULL
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
);
```

**Comment by githukueliud** [comment]
Hello

**Comment by highb33kay** [comment]
```
 "deviceId": "String",
    "deviceType": "String"
```
