### ISSUE TITLE
[FEAT]: Organization Billing Plans - Retrieve Plans for Super Admin and Owners

### ISSUE THREAD

**Issue by incredible-phoenix246** [hngprojects/hng_boilerplate_nestjs#217]
### Description

Develop endpoints to allow authenticated super admins and organization owners to retrieve available billing plans for their organization and get details of a selected billing plan. This feature will help users understand the different plans offered and choose the one that best suits their needs.

### Acceptance Criteria
- [ ] The user must be logged in and either a super admin or the owner of the organization to access these routes.
- [ ] Retrieve a list of all available billing plans for a specified organization.
- [ ] Retrieve detailed information about a selected billing plan for a specified organization.
- [ ] Ensure that users who are not the owner or super admin of the organization cannot access these routes.
- [ ] Handle cases where an invalid organization ID is provided.

### Requirements
- Ensure the user has proper authorization (super admin or organization owner) to access billing plan information.
- The user must be authenticated for these endpoints to work.
- The organization ID must be passed in the request to identify the organization.

### Endpoints

1. **Get All Billing Plans [GET]** `/api/v1/organizations/:organizationId/billing-plans`
2. **Get Billing Plan Details [GET]** `/api/v1/organizations/:organizationId/billing-plans/:planId`

### Implementation Steps

1. **Authentication and Authorization Middleware**:
    - Ensure the user is authenticated.
    - Check if the user is logged in.
    - Validate the user's session/token.
    - Ensure the user is either a super admin or the owner of the specified organization.
    - Return an error response if the user is not authorized to view the billing plans.

2. **Get All Billing Plans**:
    - Retrieve a list of all available billing plans for the specified organization from the database.
    - Return the list of billing plans in the response.

3. **Get Billing Plan Details**:
    - Retrieve the details of a specific billing plan for the specified organization using the provided plan ID.
    - Return the billing plan details in the response.

4. **Response Handling**:
    - Send a success response with the list of billing plans or the details of a specific plan.
    - Handle errors appropriately (e.g., plan not found, unauthorized access, invalid organization ID).

#### Request: Get All Billing Plans
```http
GET /api/v1/organizations/12345/billing-plans
Content-Type: application/json
Authorization: Bearer <token>
```

#### Success Response: Get All Billing Plans
```json
HTTP/1.1 200 OK
Content-Type: application/json

{
  "status": 200,
  "plans": [
    {
      "id": "basic",
      "name": "Basic Plan",
      "price": 10.00,
      "features": ["Feature 1", "Feature 2"]
    },
    {
      "id": "premium",
      "name": "Premium Plan",
      "price": 20.00,
      "features": ["Feature 1", "Feature 2", "Feature 3"]
    }
  ]
}
```

#### Request: Get Billing Plan Details
```http
GET /api/v1/organizations/12345/billing-plans/premium
Content-Type: application/json
Authorization: Bearer <token>
```

#### Success Response: Get Billing Plan Details
```json
HTTP/1.1 200 OK
Content-Type: application/json

{
  "status": 200,
  "plan": {
    "id": "premium",
    "name": "Premium Plan",
    "price": 20.00,
    "features": ["Feature 1", "Feature 2", "Feature 3"],
    "description": "Detailed description of the Premium Plan."
  }
}
```

#### Error Response: Unauthorized Access
```json
HTTP/1.1 403 Forbidden
Content-Type: application/json

{
  "status": 403,
  "error": "User is not authorized to access billing plans for this organization."
}
```

#### Error Response: Plan Not Found
```json
HTTP/1.1 404 Not Found
Content-Type: application/json

{
  "status": 404,
  "error": "Billing plan not found."
}
```

#### Error Response: Invalid Organization ID
```json
HTTP/1.1 400 Bad Request
Content-Type: application/json

{
  "status": 400,
  "error": "Invalid organization ID."
}
```

### Additional Notes
- Ensure proper error handling and response structure for consistency.
- Implement pagination if the list of billing plans is extensive.
- Consider caching the billing plans data to improve performance.

---

**Comment by markessien** [comment]
this sems to be a duplicate

**Comment by incredible-phoenix246** [comment]
@markessien the others created are for reset/forget password

**Comment by markessien** [comment]
I have seen this ticket before

**Comment by incredible-phoenix246** [comment]
I will go through all the issues again to confirm 

thank you sir

**Comment by incredible-phoenix246** [comment]
@markessien 

as promised
https://github.com/hngprojects/hng_boilerplate_nestjs/issues/99
https://github.com/hngprojects/hng_boilerplate_nestjs/issues/51


would be updating it to new tickect soon

sorry for the inconvenience

**Comment by incredible-phoenix246** [comment]
@markessien i have made the adjustments awaiting your approval
