### ISSUE TITLE
[FEAT]VALID EMAIL FORMAT-REGISTRATION FORM 

### ISSUE THREAD

**Issue by Adebimpe12** [hngprojects/hng_boilerplate_nestjs#220]
## Description
Develop an API endpoint to validate the email format provided during user registration. When a user inputs their email address, it is validated to ensure it meets the standard format (e.g., mailto:example@example.com). The system checks for the presence of the "@" symbol and a valid domain structure. If the email address is correctly formatted, it is accepted. If not, an error message is displayed, prompting the user to correct it. This ensures data integrity, user experience and successful communication.

## Acceptance Criteria

1. The endpoint `/api/v1/user/validate-email` is accessible via a POST request.
2. When a valid email format is provided, the endpoint returns a 200 OK status and a message "Email format is valid".
3. When an invalid email format is provided, the endpoint returns a 400 Bad Request status "Please enter a valid email address in the format 'example@example.com'." .
4. Ensure that all unit tests for the email validation feature are comprehensive, accurate, and verify the functionality correctly.

### Purpose
To ensure that users provide a valid email format during registration, enhancing data integrity in the database, ensures authentication is possible and improve user experience. 

### Requirements	

1. Implement an endpoint to validate email format.
2. Return appropriate status codes and messages based on the validation result.
3. Ensure secure and efficient processing of validation requests.

### Expected Outcome
An API endpoint that validates the email format during user registration and returns appropriate responses.

#### Tasks

- [ ] Create an endpoint '/api/v1/user/validate-email' to validate email format.
- [ ] Implement server-side logic to handle email format validation requests.
- [ ] Ensure secure handling of user input data.
- [ ] Write unit tests for the email validation endpoint.
- [ ] Perform security testing to ensure data protection and compliance.

##### Endpoint URL
[POST] /api/v1/user/validate-email
Request Body:
{
  "email": "string"
}

Successful Response:
Status code: 200 OK
{
"message": "Email format is valid",
"data": {
      "email": "string"
    }
  }
  
Error Response:
Status code: 400 BAD REQUEST
{
"error": "Please enter a valid email address in the format '[example@example.com](mailto:example@example.com)'."
}

#### Example Request
Validate Email Format:
curl -X POST "https://<base_url>/api/v1/user/validate-email" \
  -H "Content-Type: application/json" \
  -d '{
    "email": "[example@example.com](mailto:example@example.com)"
  }'

**Comment by highb33kay** [comment]
This is not an endpoint.

**Comment by highb33kay** [comment]
Or a feature sef. it is expected that registration or even frontend handles it
