### ISSUE TITLE
[FEAT] Real-Time Notifications [Sender]

### ISSUE THREAD

**Issue by Umaradigun** [hngprojects/hng_boilerplate_nestjs#227]
## Description
This feature will notify users instantly about important events such as messages, mentions, updates, or alerts within the platform.

#### For `POST api/v1/notifications` Endpoint

- Implement `POST v1/api/notifications` endpoint to create new notifications for users.
- Ensure the endpoint securely handles user authentication and authorization.
- Validate user input to prevent unauthorized access and ensure data integrity.
- Return a `200` status code with a success message upon successful notification creation.
- Implement error handling to return appropriate status codes (`400` for invalid requests, `500` for server errors) with meaningful error messages.
- Document the `POST v1/api/notifications` endpoint, including its purpose, parameters, and expected responses, in project documentation.

### Purpose
Develop an API for real-time notifications.

### Requirements	
- Implement `POST v1/api/notifications` endpoint to create new notifications for users.
- Ensure both endpoints integrate with existing user authentication and authorization mechanisms.
- Validate user input to prevent unauthorized access and ensure data security for both creation and retrieval of notifications.
- Return appropriate status codes (`200` for successful operations, `400` for invalid requests, `404` for not found, `500` for server errors) with meaningful error messages.
- Document each endpoint thoroughly, including its functionality, parameters, and expected responses in project documentation.

### Endpoints
**Endpoint**: `POST v1/api/notifications`

#### Create Notification

**Description**: Create a new notification for a user.
**Endpoint**: `POST v1/api/notifications`
**Request Body**:
```json
{
  "user_Id": "String",
  "type": "String",
  "message": "String",
  "data": {
    "key": "value"
  }
}
```

**Response (Success)**:
```json
{
  "status_code": 200,
  "message": "Notification created successfully."
}
```
**Response (Error)**:
```json
{
  "message": "Failed to create notification.",
  "status_code": 500
}
```

### Tasks
- [ ] Implement `POST v1/api/notifications` endpoint to create notifications.
- [ ] Ensure the endpoint handles user authentication and authorization.
- [ ] Validate user input and ensure secure retrieval of notifications.
- [ ] Implement error handling and logging for notification retrieval operations.
- [ ] Document API endpoint and usage in project documentation.

#### Unit Tests

- [ ] **Test Case 1**: Valid User ID
  - Retrieve notifications for a valid user ID.
  - Expect 200 status and valid notification data.

- [ ] **Test Case 2**: Invalid User ID
  - Attempt to retrieve notifications with an invalid user ID.
  - Expect 404 status or appropriate error message.

#### Integration Tests

- [ ] **Test Case 1**: Successful Retrieval
  - Simulate successful retrieval of notifications.
  - Expect 200 status and valid notification data.

- [ ] **Test Case 2**: Error Handling
  - Simulate internal server error during retrieval.
  - Expect 500 status and error message.

**Comment by buka4rill** [comment]
Isn't it supposed to be `/api/v1/...`

**Comment by Umaradigun** [comment]
> Isn't it supposed to be `/api/v1/...`

done

**Comment by markessien** [comment]
check that this is not a duplicate

**Comment by Benson-Ogheneochuko** [comment]
the get side is a duplicate.
here https://github.com/hngprojects/hng_boilerplate_nestjs/issues/214

**Comment by Umaradigun** [comment]
> the get side is a duplicate. here #214

ok
