### ISSUE TITLE
[FEAT] Implement GET API Endpoint for Retrieving Paginated Email Templates List by Super Admin

### ISSUE THREAD

**Issue by froschi95** [hngprojects/hng_boilerplate_nestjs#234]
## Description
Implement a RESTful API endpoint for retrieving a paginated list of email templates in the Super Admin dashboard.

## Purpose
To enable super admins to efficiently retrieve and navigate through the list of email templates used across the platform.

## Acceptance Criteria
-  Implement GET /api/v1/email-templates endpoint with pagination
-  Ensure only super admins can access this endpoint
-  Implement proper error handling and validation for template retrieval
-  Implement error handling for unauthorized access

## Requirements
- Create API endpoint for listing email templates
- Ensure only super admins can access this endpoint
- Implement pagination for retrieving email templates
- Ensure efficient querying and indexing for email templates
- Implement error handling for unauthorized access attempts

## Expected Outcome
- Fully functional API endpoint that supports retrieving a paginated list of email templates
- Secure access limited to super admins
- Efficient pagination functionality
- Proper error handling and informative error messages for template retrieval and unauthorized access

You're absolutely right, and I apologize for that oversight. Thank you for pointing that out. I'll add the 400 Bad Request error response to the API Endpoint section of the markdown. Here's the corrected version of that part:

## API Endpoint
GET /api/v1/email-templates
- Description: Retrieve a paginated list of email templates
- Query Parameters:
  - page (integer): Page number for pagination
  - limit (integer): Number of items per page
  
- Response Body (200 OK):
  ```json
  {
    "templates": [
      {
        "id": "string",
        "name": "string",
        "subject": "string",
        "content": "string",
        "created_at": "datetime",
        "updated_at": "datetime"
      }
    ],
    "total": "integer",
    "page": "integer",
    "limit": "integer"
  }
  ```
- Error Response (400 Bad Request):
  ```json
  {
    "error": "Invalid pagination parameters"
  }
  ```
- Error Response (403 Unauthorized):
  ```json
  {
    "error": "Unauthorized access"
  }
  ```
## Tasks
- [ ] Implement GET /api/v1/email-templates endpoint with pagination
- [ ] Integrate existing authentication middleware for super admin access
- [ ] Implement pagination for list endpoint
- [ ] Implement comprehensive error handling and validation for template retrieval
- [ ] Implement error handling for unauthorized access
- [ ] Write unit and integration tests for the read API endpoint

## Testing
1. Unit Tests
   - Test template retrieval functions
   - Validate input parsing and error handling for the endpoint
   - Verify that only authenticated super admins can access the endpoint
   - Test behavior with invalid pagination parameters
   - Test unauthorized access scenarios

2. Integration Tests
   - Test the entire flow of retrieving paginated templates
   - Test pagination functionality
   - Verify that the existing authentication middleware correctly restricts access to super admins
   - Test unauthorized access attempts

**Comment by markessien** [comment]
You can split this into 4 tickets

**Comment by froschi95** [comment]
@markessien this ticket has been revised as requested

**Comment by highb33kay** [comment]
Please split this into up. More than one end point here. If you cannot deliver both you FAIL.

**Comment by froschi95** [comment]
@highb33kay the ticket has been reduced to a single endpoint.
Kindly review

**Comment by highb33kay** [comment]
@froschi95 Please create a skeleton of the second ticket and share

**Comment by froschi95** [comment]
@highb33kay 
I've created the 2nd ticket as requested. Here's a [Link](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/273)

Kindly grant me access to add my team to the current ticket
