### ISSUE TITLE
[FEAT]: Database Setup and Configuration

### ISSUE THREAD

**Issue by authcornelius** [hngprojects/hng_boilerplate_nestjs#236]
#### DB Configuration
Set up a database for the chosen framework’s ORM.
- The setup should allow any database to be configured, but the default should be Postgres.
- It must follow migrations, models, and service patterns.

#### Setup Validation
To validate the setup, you must complete the following steps:

**Tables and Constraints**
- Create `users`, `profiles`, `organisations`, `products` tables.
  - A user has one profile.
  - A user has many products.
  - A user belongs to many organisations.
  - An organisation has many users.

**Tables Seeding**
- At least 2 users.
- At least 2 products per user.
- At least 3 organisations.
  - User one belongs to 2 of the organisations.
  - User two belongs to all 3 organisations.

### Endpoints

**[GET] api/v1/users/user_one_id**

Sample Response:
```json
{
  "name": "John Doe",
  "id": "some-user-id",
  "email": "johndoe@example.com",
  "profile": {
    "first_name": "John",
    "last_name": "Doe",
    "phone": "1234567890",
    "avatar_url": "http://example.com/avatar.jpg"
  },
  "organisations": [
    {
      "org_id": "some-org-id-1",
      "name": "Some Org",
      "description": "Some Org Description"
    },
    {
      "org_id": "some-other-org-id-2",
      "name": "Some Other Org",
      "description": "Some Other Org Description"
    }
  ],
  "products": [
    {
      "product_id": "some-product-id",
      "name": "Some Product",
      "description": "Some Product Description"
    },
    {
      "product_id": "some-other-product-id",
      "name": "Some Other Product",
      "description": "Some Other Product Description"
    }
  ]
}
```

**[GET] api/v1/users/user_two_id**

Sample Response:
```
{
  "name": "John Doe",
  "id": "some-user-id",
  "email": "johndoe@example.com",
  "profile": {
    "first_name": "John",
    "last_name": "Doe",
    "phone": "1234567890",
    "avatar_url": "http://example.com/avatar.jpg"
  },
  "organisations": [
    {
      "org_id": "some-org-id-1",
      "name": "Some Org",
      "description": "Some Org Description"
    },
    {
      "org_id": "some-other-org-id-2",
      "name": "Some Other Org",
      "description": "Some Other Org Description"
    },
    {
      "org_id": "some-other-org-id-3",
      "name": "Some Other Org",
      "description": "Some Other Org Description"
    }
  ],
  "products": [
    {
      "product_id": "some-product-id",
      "name": "Some Product",
      "description": "Some Product Description"
    },
    {
      "product_id": "some-other-product-id",
      "name": "Some Other Product",
      "description": "Some Other Product Description"
    }
  ]
}
```

**[POST] api/v1/products**

Request Body:
```
{
  "name": "New Product",
  "description": "Description of the new product"
}
```
Sample Response:
```
{
  "status": 201,
  "message": "Product created successfully",
  "product": {
    "product_id": "new-product-id",
    "name": "New Product",
    "description": "Description of the new product"
  }
}
```
## Purpose
This setup ensures that the database is properly configured, validated, and populated with initial data, providing a solid foundation for the application. It also allows users to create new products, saving the product ID in the database.

## Requirements

- Use an ORM to manage database operations.

- Configure the database to use PostgreSQL by default.

- Follow migration, model, and service patterns.

- Implement product creation functionality for logged-in users.

## Expected Outcome

- [ ] The database should be properly set up and validated.

- [ ] Initial data should be seeded into the database.

- [ ] Endpoints should be functional and return the expected data.

- [ ] Users should be able to create new products, and the product ID should be saved in the database.

## Implementation Steps

1. Clone the boilerplate for your Node.js Express framework.
2. Create a branch named chore/database-setup from the base branch.
3. Implement database setup, including migrations, models, and service patterns.
4. Create and seed the necessary tables.
5. Implement the endpoints for retrieving user information.
6. Implement the endpoint for creating a new product.
7. Ensure proper authentication and authorization for the product creation endpoint.
8. Validate the setup by ensuring the endpoints work as expected.

```
sql

This issue now includes the feature where a logged-in user can create a new product, and the product ID is saved in the database.
```

**Comment by nedssoft** [comment]
LGTM, go ahead and implement

**Comment by markessien** [comment]
this is a duplicate
