### ISSUE TITLE
[FEAT] API  Endpoint to delete a testimonial

### ISSUE THREAD

**Issue by Amal-Salam** [hngprojects/hng_boilerplate_nestjs#238]
## Description
Develop an api endpoint to handle the deletion of a testimonial. This api will validate the testimonial_id
## Acceptance Criteria
- [ ] Only authenticated users with admin permisssions can delete testimonials.
- [ ] The endpoint should be accessible at `api/v1/testimonials/:testimonial_id`
- [ ] The endpoint should accept HTTP DELETE requests.
- [ ] The endpoint should be protected and require authentication
- [ ] Request to the endpoint should include a valid authentication token in Authorization header . Authorization: `Bearer <token>`
- [ ] Return appropriate response and status code
### Purpose
Delivers a api that manages testimonial deletion and verifies the validity of the testimonial ID.
### Requirements
Data Validation:
The api should validate the request to ensure that the testimonial id is present and valid
### Expected Outcome
Successful deletion of testimonial with selected testimonial id.
### Endpoint:
HTTP [DELETE] /api/v1/testimonials/:testimonial_id
### API Request Example:
`DELETE /api/v1/testimonials/:testimonial_id`
```json
{
  "Content-Type": "application/json",
  "Authorization": "Bearer <token>"
}
```
## API Successful Response
```json
{
  "success": true,
  "message": "string",
  "status_code": 200
}
```
### Bad request
```json
{
  "message": "string",
  "error": "string",
  "status_code": 400
}
```
### Unauthorized
```json
{
  "message": "string",
  "error": "string",
  "status_code": 401
}
```
### Not Found
```json
{
  "message": "string",
  "error": "string",
  "status_code": 404
}
```
### Server Error
```json
{
  "message": "string",
  "error": "string",
  "status_code": 500
}
```
### Tasks
- [ ] Develop server-side logic to handle testimonial deletion requests.
- [ ] Validate incoming testimonial ID data.
- [ ] Validate the user deleting the testimonial is an admin.
### Testing
- [ ] Write unit tests for the delete testimonial logic.
- [ ] Test various scenarios such as deleting existing testimonials, attempt without authentication or proper permissions, deleting
      fictitious testimonial.

**Comment by Amal-Salam** [comment]
Team members include
[bruce-pain](https://github.com/bruce-pain)  slack-id : @batman.py
noblehart8@gmail.com slack-id: @Redington
