### ISSUE TITLE
[FEAT] Create API Endpoint to fetch an image

### ISSUE THREAD

**Issue by Samilincoln** [hngprojects/hng_boilerplate_nestjs#240]
## Description
 Creating an API endpoint for getting an image by slug, with resizing and caching.

## Acceptance Criteria
1. **Read Image**
   - Users can fetch an image.
   - Appropriate error messages for not found or unauthorized requests.
   - Image resixing functionality.
   - Caching

### Purpose
The purpose of this project is to allow users to access an image through a well-defined API.

### Requirements
**Read Images**
   - Fetch an image with authorized token and slug.
   - Optionally resize the image.

### Expected Outcome
Users should be able to get an image through a secure API with optional resizing, caching and appropriate responses.

## API Endpoint
- **GET /v1/api/images/**: Fetch specific image by slug with optional resizing.

**Request with resizing**
```
GET /v1/api/images/image-slug?width=300&height=300 HTTP/1.1
Host: example.com
Authorization: Bearer <token>

```

**Request without resizing**
```
GET /v1/api/images/image-slug HTTP/1.1
Host: example.com
Authorization: Bearer <token>

```

**Response body (success)**
```JSON
{
    "slug": "image-slug",
    "url": "https://example.com/image1.jpg",
    "description": "Sample image 1",
    "timestamp": "2024-07-17T12:00:00Z"
}

```

**Response body (error)**
```JSON
{
  "error": "Not Found",
  "message": "Image with the given slug not found."
},
{
  "error": "Unauthorized",
  "message": "Authentication token is missing or invalid."
}

```

### Tasks
- [ ] Create API endpoints to fetch an image.
- [ ] Add resizing functionality.
- [ ] Implement caching for images.

 1.**Resizing**
- [ ] Implement image resizing based on query parameters (width, height).
- [ ] Validate resizing parameters.

 2.**Caching**
- [ ] Implement caching mechanism for fetched images.
- [ ] Ensure cache invalidation for updated or deleted images.

### Testing
**Test GET /v1/api/images/**
- [ ] Test fetching an image with a valid slug and token.
- [ ] Test fetching an image with an invalid slug.
- [ ] Test unauthorized access without a token.
- [ ] Test image resizing functionality.
- [ ] Test caching mechanism for performance improvements.

**Comment by markessien** [comment]
You do not typically retrieve images with Id, but with a slug, which corresponds to the file url. You also would want to introduce a resizing functionality, as well as caching. You can split out resize and caching into two separate tickets

**Comment by Samilincoln** [comment]
> You do not typically retrieve images with Id, but with a slug, which corresponds to the file url. You also would want to introduce a resizing functionality, as well as caching. You can split out resize and caching into two separate tickets

Endpoint has been updated to retrieve images with slug, resizing functionality, and caching added too.
Ticket was split into two subtickets for both caching and resizing.

Awaiting your review for feedbacks
