### ISSUE TITLE
[FEAT]: Implement endpoint to update notification settings

### ISSUE THREAD

**Issue by bruce-pain** [hngprojects/hng_boilerplate_nestjs#241]
## Description

Create an endpoint to update user notification settings

## Acceptance Criteria

**Endpoint implementation**:

- The endpoint should be accessible at `/api/v1/settings/notification-settings`

- The endpoint should only accept HTTP `PATCH` requests

**Endpoint security**:

- Only authenticated users can have access to the endpoint
- A user must have the appropriate permissions to access the endpoint
- Each request to the endpoint must include a valid authentication token in the Authorization header
- `Authorization: Bearer <token>`

**Validation**:

- The endpoint should check whether the provided `user_id` is valid, that is, the `user_id` exists in the database.

  - If the validation fails (user does not exist):
    - send an error response with HTTP status code of `404` (Not Found)
  - If the validation succeeds (user exists):
    - proceed to perform data validation on the request body

- The endpoint should validate the data being sent in the request body
  - the request body should contain at least one of the following keys:
    - `email_notifications`
    - `push_notifications`
    - `sms_notifications`
  - each key only accepts a boolean value `true | false`
  - if the request body contains any unspecified keys or a non-boolean value:
    - send an error response with HTTP status code of `400` (Bad Request)
  - if the request body is successfully validated:
    - retrieve the user notification settings from the database
    - modify the fields specified by the keys in the request body (at least one field can be modified)
    - save the modified user notification settings to the database
    - send a success response with HTTP status code of `200` (OK)

### Sample Request

Route: `PATCH` `/api/v1/settings/notification-settings`

- Query parameters:

  - `user_id`: UUID string

- **Request Body**:

  ```json
  {
    "push_notifications": true
  }
  ```

### Accessing Protected Routes

**Authorization Header**:

- Given a valid token in the Authorization header, the system should allow access and return the requested data when the user accesses a protected route.

  ```json
  {
    "Authorization": "Bearer <token>"
  }
  ```

- When a request is given without an authorization header or with an invalid token, when the user accesses a protected route, the system should return 401 Unauthorized status.

### Sample Response

- **successful response**

  `user_id` is valid and user notification settings have successfully been updated

  ```json
  {
    "status": "success",
    "message": "User notification settings updated successfully",
    "status_code": 200
  }
  ```

- **unsuccessful response**

  - `user_id` is invalid and user notification settings cannot be updated

    ```json
    {
      "status": "error",
      "message": "User not found",
      "status_code": 404
    }
    ```

  - request body contains invalid data

    ```json
    {
      "status": "error",
      "message": "Invalid data in the request body",
      "status_code": 400
    }
    ```

  - The user is unauthorized and cannot access the endpoint

    ```json
    {
      "status": "error",
      "message": "Access denied, Unauthorized request",
      "status_code": 401
    }
    ```

### Purpose

The endpoint allows users to manage and update their notification settings

### Requirements

- [ ] Ensure an authenticated user is accessing the endpoint
- [ ] Ensure that user can only modify their own notification settings
- [ ] Develop server-side logic to update the user notification settings
- [ ] Ensure that data modification complies with security standards
- [ ] Ensure that updated data is stored correctly in the database

### Expected Outcome

A secured API endpoint that enables a user to update their own notification settings

### Tasks

- [ ] Implement the endpoint route `/api/v1/notification-settings/{:user_id}`
- [ ] Perform the appropriate database operations required to modify user settings and safely store the updates
- [ ] Ensure that only authorized users can access the endpoint
- [ ] Implement error handling for scenarios when the user is unauthorized and invalid data, with the appropriate HTTP status codes
- [ ] Ensure the endpoint returns the appropriate response body

### Testing

- Unit testing for the API endpoint, covering authentication logic, update, error handling etc
- Integration testing to ensure end-to-end functionality.
- Security testing for data protection
