### ISSUE TITLE
[FEAT] API Endpoint to fetch single Job listing 

### ISSUE THREAD

**Issue by aniebietafia** [hngprojects/hng_boilerplate_nestjs#249]
## Description
Select a single job listing by Id. 

## Acceptance Criteria

- The endpoint should be accessible at `GET /api/v1/jobs/:job_id`
- User should be authenticated to access the endpoint.
- The endpoint should return a `404` status code if the job listing does not exist.
- The endpoint should return a `401` status code if the user is not authenticated.
- The endpoint should return a `200` status code if the job listing is fetched.
- The endpoint should return the job listing.

### Purpose

Be able to view a single job listing in order to get more details about the job requirements. 

### Requirements

- Implement API endpoint for fetching job listing.
- Job listing should be fetched successfully if it exists. 
- Handle unexpected errors and return the appropriate status code.

### API Endpoint

```http
GET /api/v1/jobs/:job_id
```

#### Response

```json
{
  "message": "Job listing fetched successfully",
  "status_code": 200,
  "data": {
    "id": "String",
    "title": "String",
    "description": "String",
    "location": "String",
    "salary": "String",
    "job_type": "String",
    "created_at": "DateTime",
    "company_name": "String"
  }
}
```

#### Error Responses

```json
{
  "status": 404,
  "error": "Job listing not found"
}
```

```json
{
  "status": 401,
  "error": "Unauthorized "
}
```

### Expected Outcome

User should be able to view job listing and all of its details and requirements. 

### Tasks
- [ ] Develop API endpoint to view job listing.
- [ ] Return proper error cases.
- [ ] Write tests for the API endpoint.

### Testing

- Unit tests should be written for the API endpoint.
- Integration tests should be written for the API endpoint.

**Comment by markessien** [comment]
I think this is a duplicate

**Comment by highb33kay** [comment]
@aniebietafia 

Issue duplicate of #72
