### ISSUE TITLE
[FEAT] Implement Blog Search and Filtering API

### ISSUE THREAD

**Issue by Ibukun-AL** [hngprojects/hng_boilerplate_nestjs#25]
# Implement Blog Search and Filtering API

## Description

Creating an API that allows visitors to search and filter through blog content on the site without authentication, providing quick access to relevant articles and information.

#### Purpose

To enable users to search and filter blog posts based on various criteria such as author, title, content, tags, and creation date, while implementing robust security measures to protect data and prevent abuse.

#### Requirements

- [ ] Develop a RESTful API endpoint (`GET /api/v1/blogs/search`) to handle requests for searching and filtering blog posts.
- [ ] Implement server-side validation and sanitization of user input to prevent injection attacks and ensure data integrity.
- [ ] Implement logging mechanisms to track API requests and responses for auditing and debugging purposes.
- [ ] Integrate with Typesense service for efficient and scalable search functionality.
- [ ] Implement pagination to manage the number of results returned in a single response.

#### Expected Outcome

The backend should provide a reliable API endpoint that allows users to search and filter blog content securely and efficiently. It should handle requests based on specified criteria, including content, creation date (`createdDate`), and tags, while adhering to high-security standards.
Additionally, the API should support pagination to ensure manageable response sizes.

#### Endpoints

**Fetch Blogs:**

- **Description:** Provides a list of blog posts based on search and filter criteria.
- **Endpoint:** `GET /api/v1/blogs/search`

**Request Parameters:**

- `author`: String (optional) - Author name to filter by.
- `title`: String (optional) - Title or part of a title to filter by.
- `content`: String (optional) - Content or part of the content to filter by.
- `tags`: String (optional) - Tags associated with the blog post to filter by.
- `createdDate`: String (optional) - Date for filtering blog posts created on or after this date (format: YYYY-MM-DD).
- `page`: Int (optional) - Page number for pagination.
- `pageSize`: Int (optional) - Number of results per page.

**Successful Response:**

```json

 {
  "currentPage": Int,
  "totalPages": Int,
  "totalResults": Int,
  "blogs": [
    {
      "id": "String",
      "title": "String",
      "content": "String",
      "author": "String",
      "createdDate": "String",
      "tags": ["String"]
    }
  ],
  "meta":{
    "hasNext": true,
    "total": 100,
    "nextPage": 2,
    "prevPage": null
  }
}

```

### Error Response

```json
{
  "message": "String",
  "error": "String",
  "statusCode": Int
}
```

### Tasks

- [ ] Develop a secure GET endpoint** (`/api/blogs/search`) to fetch blog posts based on search and filter criteria.

- [ ] Ensure server-side validation and sanitization** of user input to prevent security vulnerabilities.

- [ ] Configure logging to capture API activities and errors for monitoring and troubleshooting.

- [ ] Integrate with Typesense service for efficient search functionality.

- [ ] Implement pagination logic to handle page and pageSize parameters and return paginated results.

### Testing

- Write **comprehensive unit tests** to validate backend logic, including input validation, filtering, pagination, and response formatting.
  
- Conduct **integration tests** to verify endpoint functionality and interaction with database queries.
  
- Perform **security testing** to identify and address potential vulnerabilities, ensuring robust data protection measures.

**Comment by markessien** [comment]
Remove the rate limiting feature, as its overkill. There is no need to specify something that is a given like "https protocol". I do not see how search is encrypted in the db.

Search in general should be done via a single typesense service.

**Comment by Ibukun-AL** [comment]
I've updated the issue description based on recent feedback and project requirements. Key changes include:

1. Removed the rate limiting requirement as it was deemed unnecessary for this implementation.

2. Eliminated the explicit mention of HTTPS protocol, as it's considered a standard practice.

3. Removed references to encrypting search data in the database. This isn't typically done for search functionality as it would hinder performance and isn't necessary for public blog content.

4. Added a requirement to integrate with Typesense service for efficient search functionality. This replaces the previous generic search implementation.

**Comment by NdubuisiJr** [comment]
@darionnuel this endpoint should be paginated

**Comment by darionnuel** [comment]
I have updated endpoint to include pagination as requested.
The endpoint now accepts page and pageSize parameters to give out a paginated response. 
I also edited the successful response, requirements and acceptance criteria, and tasks and testing sections to account for the new pagination logic.

**Comment by Ace2489** [comment]
Here.

**Comment by darionnuel** [comment]
Team Members

@Ibukun-AL Spring Boot
@Dricy FastAPI
@Ace2489 .NET
@darionnuel Nestjs

**Comment by Dricy** [comment]
here

**Comment by NdubuisiJr** [comment]
@darionnuel the response should contain the following pagination meta data.
```Js
{
   ...
   meta: {
     has_next: boolean,
     total: number,
     next_page: number | null,
     prev_page: number | null
  }
}
```

**Comment by darionnuel** [comment]
I cannot edit the issue any longer. It seems that I have been removed as a maintainer from the repo even though I am the team lead for my team.

**Comment by Ibukun-AL** [comment]
Updated the GitHub issue to reflect the new response structure

**Comment by Popsicool** [comment]
@darionnuel the response ought to be an object of objects, not an array of object. Remove the  [] around the object you are returning

**Comment by Ibukun-AL** [comment]
Updated the response structure
