### ISSUE TITLE
[FEAT] API to fetch Single Testimonial

### ISSUE THREAD

**Issue by aniebietafia** [hngprojects/hng_boilerplate_nestjs#255]
## Description
Fetch a single testimonial by Id. 

## Acceptance Criteria

- The endpoint should be accessible at `GET /api/v1/testimonials/:testimonial_id`
- User should be authenticated to access the endpoint.
- The endpoint should return a `404` status code if the testimonial does not exist.
- The endpoint should return a `401` status code if the user is not authenticated.
- The endpoint should return a `200` status code if the testimonial is fetched.
- The endpoint should return a single testimonial.
- The endpoint must accept access token `Authorization: Bearer: <token>`

### Purpose

Be able to view a single testimonial and leave a comment. 

### Requirements

- Implement API endpoint for single testimonial.
- Testimonial should be fetched successfully if it exists. 
- Handle unexpected errors and return the appropriate status code.
- User must be authenticated to access this endpoint.
- The endpoint must accept access token `Authorization: Bearer: <token>`

### API Endpoint

```http
GET /api/v1/testimonials/: testimonial_id
```

#### Response

```json
{
  "message": "Testimonial fetched successfully",
  "status_code": 200,
  "data": {
    "id": "String",
    "author": "String",
    "testimonial": "String",
    "comments": Array, 
    "created_at": "DateTime",
  }
}
```

#### Error Responses

```json
{
  "status_code": 404,
  "message": "Testimonial not found"
}
```

```json
{
  "status_code": 401,
  "message": "Unauthorized "
}
```

### Expected Outcome

User should be able to view Single Testimonial and all the comments associated with it. 

### Tasks
- [ ] Develop API endpoint to view Testimonial.
- [ ] Return proper error cases.
- [ ] Write tests for the API endpoint.

### Testing

- Unit tests should be written for the API endpoint.
- Integration tests should be written for the API endpoint.

**Comment by aniebietafia** [comment]
This ticket has not been handled. This is the first issue created for it.

**Comment by phurhard** [comment]
@Shullyd7 or @highb33kay . Check this!

**Comment by phurhard** [comment]
Your error response is t following the convention.
Instead of "error", you should be using "message".

Also provide the request body

**Comment by Shullyd7** [comment]
You request is not accepting the user token

**Comment by aniebietafia** [comment]
Oh. I sincerely apologize, I ommitted that but it is fixed now.

**Comment by FreemanBoss** [comment]
These issues is initiated by 5 interns.
- @aniebiet
- Habeeb Babasulaiman 
- @Ubong Patrick
- @iotstudent
- Joshua Temitope
