### ISSUE TITLE
[FEAT]: API Endpoint For Removing Roles within an Organisation

### ISSUE THREAD

**Issue by traderstechie** [hngprojects/hng_boilerplate_nestjs#256]
## Description:
Develop and integrate an API endpoint to facilitate the removing of single role within an organization.

### Scope
- Design and implement a RESTful API endpoint for deleting a single role
- Use OrganizationGuard to handle organization context
- Ensure proper authentication and authorization checks
- Validate input data and handle edge cases
- Implement necessary database operations
- Provide appropriate error handling and response formatting

### Specific Requirements
1. Implement ``` DELETE /api/v1/roles/{role-id} ``` endpoint
2. Use OrganizationGuard to extract and validate organization context
3. Ensure authentication using JWT tokens
4. Authorize users based on their permissions within the organization
5. Validate the role ID format
6. Check if the role is currently assigned to any users before deletion
7. Implement soft delete for roles to maintain data integrity
8. Handle cases where the role or organization does not exist

### Path Parameters:
``` role-id ```: string, required (UUID format)

### Success Response (200 OK)
```
{
  "status_code": 200,
  "message": "Role successfully removed"
}
```

### Error Responses 400 
**Bad Request**
```
{
  "status_code": 400,
  "error": "Bad Request",
  "message": "Invalid role ID format" 
}
```

**404 Not Found (Role)**
```
{
  "status_code": 404,
  "error": "Not Found",
  "message": "The role with ID ${id} does not exist"
}
```

## Tasks
- [ ] Set up endpoint for deleting a single role
- [ ] Implement OrganizationGuard
- [ ] Authentication and Authorization of roles/{role-id} DELETE endpoint
- [ ] Validate role ID format
- [ ] Implement database query to check if the role is assigned to any users
- [ ] Implement soft delete operation for roles
- [ ] Implement error handling for various scenarios (invalid ID, non-existent role, role in use)
- [ ] Testing
  - Write unit tests for the role deletion endpoint
  - Write integration tests for the role deletion endpoint
  - Test error scenarios (invalid ID, non-existent role, non-existent organization, role in use)
- [ ] Documentation
  - Update API documentation with new endpoint details
  - Include examples of successful and error responses
- [ ] Security considerations
  - Ensure that only users with appropriate permissions can delete roles

**Comment by traderstechie** [comment]
Please, the **Disable Role API** issue was initially created by @PearlPerfect, who brought me on as a FastAPI dev, [Here](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/176). But due to some circumstances, she had to close the first issue and we agreed that I should open a new one. That's why this issue exists.

**Comment by highb33kay** [comment]
What is the Default role?

Need more information before second approval 

@traderstechie

**Comment by highb33kay** [comment]
Please see #235

**Comment by traderstechie** [comment]
Okay @highb33kay I'm working with the database designer to include a generic default **Role** for all organizations that'll have the basic permissions required to be an ordinary member of an organization. So each time a *Role* is disable, all users who were previously on it would be moved to the default role.

**Comment by highb33kay** [comment]
Can you add the details there. The PMS are the ones tracking not me.

**Comment by traderstechie** [comment]
> Please see #235

I've also check [Issue 235](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/235), I see that [Issue 246](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/246) and mine, relating to each other, are referenced there. But, please, may I know what more to do with the info aside checking out the related feature and making sure everything is in sync?

**Comment by highb33kay** [comment]
@Shullyd7 Can we get second approval here

**Comment by highb33kay** [comment]
I meant check the way the issue was structured @traderstechie

**Comment by traderstechie** [comment]
> I meant check the way the issue was structured @traderstechie

Okay, sir.

**Comment by traderstechie** [comment]
> @Shullyd7 Can we get second approval here

Thank you @highb33kay 

cc @Shullyd7

**Comment by Shullyd7** [comment]
This API should be protected. Update the request body and add error for unrecognised user @traderstechie

**Comment by PearlPerfect** [comment]
> This API should be protected. Update the request body and add error for unrecognised user @traderstechie

We are not working directly with the user table, roles are within organizations, an admin in an organization can only disable roles within than organization...

So, do you mean adding an error for unrecognized role???

**Comment by highb33kay** [comment]
He means to identify that this is a protected route in your documentation. 

Should have examples of the Request Auth and type tc.

**Comment by traderstechie** [comment]
Hi @Shullyd7, thanks for pointing out the needed corrections! I've made the updates as you pointed out. Please review.

cc @highb33kay

**Comment by highb33kay** [comment]
@Shullyd7 if you are good, boss.

**Comment by traderstechie** [comment]
Thank you @highb33kay  and @Shullyd7
