### ISSUE TITLE
[FEAT] Implement API Endpoint to Assign Role and Permissions to a User within an Organization

### ISSUE THREAD

**Issue by Takinnuoye5** [hngprojects/hng_boilerplate_nestjs#259]
### Description
Develop and integrate a complete Role-Based Access Control (RBAC) system into the application to manage user permissions and access levels. This includes endpoints for creating permissions, roles, assigning roles to users, and checking permissions.

### Acceptance Criteria:
1. Create Permission Endpoint:

- Endpoint: The endpoint /api/v1/permissions should be accessible via a POST request.
- Request Body: The request body should include the permission name and description.
- Successful Creation: When a valid permission name and description are provided, the endpoint returns a 201 Created status with a success message and the details of the created permission.
- Permission Already Exists: If a permission with the same name already exists, the endpoint returns a 409 Conflict status with an appropriate error message.

2. Create Role Endpoint:

- Endpoint: The endpoint /api/v1/roles should be accessible via a POST request.
- Request Body: The request body should include the role name and an array of permission_ids.
- Successful Creation: When a valid role name and permissions are provided, the endpoint returns a 201 Created status with a success message and the details of the created role.
- Role Already Exists: If a role with the same name already exists, the endpoint returns a 409 Conflict status with an appropriate error message.
- Invalid Permission: If any provided permission_id does not exist, the endpoint returns a 404 Not Found status with an appropriate error message.

3. Assign Role to User Endpoint:

- Endpoint: The endpoint /api/v1/organizations/{organization-id}/users/{user-id}/roles should be accessible via a POST request.
- Request Body: The request body should include the role_id to be assigned to the user.
- Successful Assignment: When valid organization-id, user-id, and role_id are provided, the endpoint returns a 200 OK status with a success message.
- Invalid Format: When an invalid organization-id or user-id format is provided, the endpoint returns a 400 Bad Request status with an appropriate error message.
- Role Not Found: When a role_id that does not exist is provided, the endpoint returns a 404 Not Found status with an appropriate error message.
- User or Organization Not Found: When an organization-id or user-id that does not exist is provided, the endpoint returns a 404 Not Found status with an appropriate error message.
- Server Error: If an unexpected server error occurs, the endpoint returns a 500 Internal Server Error status with an appropriate error message.

4. Check Permissions Endpoint:

- Endpoint: The endpoint /api/v1/users/{user-id}/permissions should be accessible via a GET request.
- Response: The endpoint returns a 200 OK status with the list of permissions assigned to the user.
- User Not Found: If the user-id does not exist, the endpoint returns a 404 Not Found status with an appropriate error message.

Create Permission Endpoint
Endpoint URL:

```
bash

POST /api/v1/permissions
```
Request Body:
```
json

{
  "name": "update_profile",
  "description": "Allows the user to update their profile information"
}
```
Responses:

Success Response:

Code: 201 Created
Content:
```
json

{
  "message": "Permission created successfully",
  "status_code": 201,
  "data": {
    "id": "permission-id",
    "name": "update_profile",
    "description": "Allows the user to update their profile information",
    "created_at": "DateTime"
  }
}
```
Error Responses:

Code: 400 BAD REQUEST
Content:
```
json

{
  "status_code": 400,
  "message": "Invalid permission name or description format"
}
```
Code: 409 CONFLICT
Content:
```
json

{
  "status_code": 409,
  "message": "Permission already exists"
}
```
Code: 500 INTERNAL SERVER ERROR
Content:
```
json
{
  "status_code": 500,
  "message": "An unexpected error occurred"
}
```
Create Role Endpoint
Endpoint URL:
```
bash

POST /api/v1/roles
```

Request Body:
```
json

{
  "name": "admin",
  "permission_ids": ["1", "3", "5"]
}
```
Responses:

Success Response:

Code: 201 Created
Content:
```
json

{
  "message": "Role created successfully",
  "status_code": 201,
  "data": {
    "id": "role-id",
    "name": "admin",
    "permissions": [
      {"id": "1", "name": "create_user"},
      {"id": "3", "name": "delete_user"},
      {"id": "5", "name": "update_user"}
    ],
    "created_at": "DateTime"
  }
}
```
Error Responses:

Code: 400 BAD REQUEST
Content:
```
json

{
  "status_code": 400,
  "message": "Invalid role name or permission_ids format"
}
```
Code: 404 NOT FOUND
Content:
```
json

{
  "status_code": 404,
  "message": "One or more permissions not found"
}
```
Code: 409 CONFLICT
Content:
```
json

{
  "status_code": 409,
  "message": "Role already exists"
}
```
Code: 500 INTERNAL SERVER ERROR
Content:
```
json

{
  "status_code": 500,
  "message": "An unexpected error occurred"
}
```
Assign Role to User Endpoint
Endpoint URL:
```
bash
POST /api/v1/organizations/{organization-id}/users/{user-id}/roles
```
Request Body:
```
json
{
  "role_id": "role-id"
}
```
Responses:

Success Response:

Code: 200 OK
Content:
```
json

{
  "message": "Role assigned successfully",
  "status_code": 200,
  "data": {
    "id": "user-id",
    "organization_id": "organization-id",
    "role": "admin",
    "permissions": [
      {"id": "1", "name": "create_user"},
      {"id": "3", "name": "delete_user"},
      {"id": "5", "name": "update_user"}
    ],
    "created_at": "DateTime"
  }
}
```
Error Responses:

Code: 400 BAD REQUEST
Content:
```
json

{
  "status_code": 400,
  "message": "Invalid organization ID or user ID format"
}
```
Code: 404 NOT FOUND
Content:
```
json

{
  "status_code": 404,
  "message": "Organization, user, or role not found"
}
```
Code: 422 UNPROCESSABLE CONTENT / VALIDATION ERROR
Content:
```
json

{
  "status_code": 422,
  "message": "Validation error",
  "errors": {
    "field": "<field>",
    "message": "<message>"
  }
}
```
Code: 500 INTERNAL SERVER ERROR
Content:
```
json

{
  "status_code": 500,
  "message": "An unexpected error occurred"
}
```
Check Permissions Endpoint
Endpoint URL:
```
bash

GET /api/v1/users/{user-id}/permissions
```
Responses:

Success Response:

Code: 200 OK
Content:
```
json

{
  "status_code": 200,
  "message": "Permissions fetched successfully",
  "data": {
    "id": "user-id",
    "permissions": [
      {"id": "1", "name": "create_user"},
      {"id": "3", "name": "delete_user"},
      {"id": "5", "name": "update_user"}
    ],
    "created_at": "DateTime"
  }
}
```
Error Responses:

Code: 404 NOT FOUND
Content:
```
json

{
  "status_code": 404,
  "message": "User not found"
}
```
Code: 500 INTERNAL SERVER ERROR
Content:
```
json

{
  "status_code": 500,
  "message": "An unexpected error occurred"
}
```
Database Schema:
```
sql

Table users {
  id int [pk, increment]
  name varchar(255) [not null]
  email varchar(255) [not null, unique]
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
}

Table organizations {
  id int [pk, increment]
  name varchar(255) [not null]
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
}

Table permissions {
  id int [pk, increment]
  name varchar(255) [not null, unique]
  description text [not null]
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
}

Table roles {
  id int [pk, increment]
  name varchar(255) [not null, unique]
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
}

Table role_permissions {
  id int [pk, increment]
  role_id int [ref: > roles.id]
  permission_id int [ref: > permissions.id]
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
}

Table user_roles {
  id int [pk, increment]
  user_id int [ref: > users.id]
  organization_id int [ref: > organizations.id]
  role_id int [ref: > roles.id]
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
}
```

### Purpose:

- The Create Permission endpoint allows for the creation of new permissions.
- The Create Role endpoint allows for creating roles and assigning existing permissions to these roles.
- The Assign Role to User endpoint allows for assigning existing roles to users within an organization.
- The Check Permissions endpoint allows for retrieving the permissions of a user.

### Requirements:

- Implement the Create Permission endpoint to create new permissions.
- Implement the Create Role endpoint to create new roles with assigned permissions.
- Implement the Assign Role to User endpoint to assign existing roles to users.
- Implement the Check Permissions endpoint to retrieve a user's permissions.
- Return detailed information on the created or assigned roles and permissions.
- Handle situations where permissions, roles, users, or organizations do not exist.

### Expected Outcome:

- Four API endpoints that manage permission creation, role creation with permissions, role assignment to users, and permission retrieval, ensuring clear and effective role and permission management within the system.

### Tasks:

1.Define Create Permission Endpoint:

- [ ] Create an endpoint /api/v1/permissions to create permissions.

2. Define Create Role Endpoint:

- [ ] Create an endpoint /api/v1/roles to create roles with permissions.

3. Define Assign Role to User Endpoint:

- [ ] Create an endpoint /api/v1/organizations/{organization-id}/users/{user-id}/roles to assign roles and permissions.

4. Define Check Permissions Endpoint:

- [ ] Create an endpoint /api/v1/users/{user-id}/permissions to retrieve user permissions.

5. Implement Logic:

- [ ] Implement server-side logic to handle successful and failed permission creation, role creation, role assignment, and permission retrieval requests.

6. Input Validation:

- [ ] Ensure input validation to verify the correctness of permission names, role names, permission IDs, organization-id, and user-id.

7. Database Query:

- [ ] Write the necessary database queries to create permissions, create roles with assigned permissions, update user roles and permissions, and retrieve user permissions.

8. Error Handling:

- [ ] Implement error handling for invalid inputs, non-existing permissions, roles, users, or organizations, and server errors.

9. Logging:

- [ ] Implement logging for errors and role assignment or creation attempts.

10. Testing:

- [ ] Write unit tests for the permission creation, role creation, role assignment, and permission retrieval endpoints.
- [ ] Write integration tests for the permission creation, role creation, role assignment, and permission retrieval logic.

11. Security:

- [ ] Perform security testing to ensure data protection and compliance.
- [ ] Ensure all sensitive data is encrypted and secure.

**Comment by highb33kay** [comment]
Request Body or Params?

How is the role or user identified or add in the URL?

@Takinnuoye5

**Comment by Takinnuoye5** [comment]
@highb33kay boss I have made necessary amendments please assist confirm if requirement was met

**Comment by highb33kay** [comment]
I still have questions about this. One is are the roles being created or assigned?

**Comment by Takinnuoye5** [comment]
@highb33kay so the role must already exist within the system. But then I don’t know if I should create the role and assign together

**Comment by phurhard** [comment]
@highb33kay approve if satisfied with his changes

**Comment by highb33kay** [comment]
Not satisfied because I think this is how it should be. 

Permissions exists 

Create this 
Update 
Read
Execute 
Update credit card
Update role
Delete role 
Etc.

Then roles should be created with an endpoint that assigns these permissions to the roles 

Role : permission [1, 3,8]


So when we are running auth checks we check for permissions not roles 

This is just a summary of how I think it should go. 

This would allow us generate dynamic roles and not static roles

**Comment by highb33kay** [comment]
@phurhard Let me know what you think

**Comment by highb33kay** [comment]
@Takinnuoye5 See also #153

**Comment by highb33kay** [comment]
So IMO we need a create role that takes in permission and also to assign role

**Comment by Takinnuoye5** [comment]
okay i will factor this into it immediately boss

**Comment by highb33kay** [comment]
Did you see my comment on the other issue? About permissions and roles being dynamic?

**Comment by Takinnuoye5** [comment]
hello boss , @highb33kay  please check the new structure

**Comment by highb33kay** [comment]
This looks good, I just think it is too many endpoints for one ticket.

**Comment by Takinnuoye5** [comment]
can i create three tickets then , to cater for it

**Comment by highb33kay** [comment]
@Takinnuoye5 you still here?

**Comment by Takinnuoye5** [comment]
Yes i am asking if i can create 3 tickets so to ensure I cover everything on user roles and permissions

**Comment by Takinnuoye5** [comment]
@highb33kay i have agreed to go with the Create Permission Endpoint: while the rest Endpoints have been shared accordingly

**Comment by highb33kay** [comment]
Alright, niceee.
