### ISSUE TITLE
[FEAT] Implement GET API Endpoint for Retrieving a Specific Email Template By ID For Super Admin

### ISSUE THREAD

**Issue by froschi95** [hngprojects/hng_boilerplate_nestjs#273]
## Description
Implement a RESTful API endpoint for retrieving a specific email template by its ID in the Super Admin dashboard.

## Purpose
To enable super admins to retrieve detailed information about a single email template used in the platform.

## Acceptance Criteria
- [ ] Implement GET /api/v1/email-templates/{id} endpoint
- [ ] Ensure only super admins can access this endpoint
- [ ] Implement proper error handling and validation for template retrieval
- [ ] Implement error handling for unauthorized access and not found scenarios

## Requirements
- Create API endpoint for retrieving a specific email template by ID
- Ensure only super admins can access this endpoint
- Implement error handling for unauthorized access attempts and not found scenarios

## Expected Outcome
- Fully functional API endpoint that supports retrieving a specific email template
- Secure access limited to super admins
- Proper error handling and informative error messages for template retrieval, unauthorized access, and not found scenarios

## API Endpoint
GET /api/v1/email-templates/{id}
- Description: Retrieve a specific email template
- Path Parameters:
  - id (string): Unique identifier of the email template
- Response Body (200 OK):
  ```json
  {
    "id": "string",
    "name": "string",
    "subject": "string",
    "content": "string",
    "created_at": "datetime",
    "updated_at": "datetime"
  }
  ```
- Error Response (400 Bad Request):
  ```json
  {
    "error": "Invalid template ID format"
  }
  ```
- Error Response (403 Unauthorized):
  ```json
  {
    "error": "Unauthorized access"
  }
  ```
- Error Response (404 Not Found):
  ```json
  {
    "error": "Template not found"
  }
  ```

## Tasks
- [ ] Implement GET /api/v1/email-templates/{id} endpoint
- [ ] Integrate existing authentication middleware for super admin access
- [ ] Implement comprehensive error handling and validation for template retrieval
- [ ] Implement error handling for unauthorized access and not found scenarios
- [ ] Write unit and integration tests for the read API endpoint

## Testing
1. Unit Tests
   - Test template retrieval function
   - Validate input parsing and error handling for the endpoint
   - Verify that only authenticated super admins can access the endpoint
   - Test behavior with invalid template IDs
   - Test unauthorized access scenarios
   - Test not found scenarios

2. Integration Tests
   - Test the entire flow of retrieving a specific template
   - Verify that the existing authentication middleware correctly restricts access to super admins
   - Test unauthorized access attempts
