### ISSUE TITLE
[FEAT] API Endpoint to Fetch All Roles within an Organisation. 

### ISSUE THREAD

**Issue by Adebimpe12** [hngprojects/hng_boilerplate_nestjs#288]
## Description
Develop and integrate an API endpoint to facilitate the fetching of roles within an organization 

### Scope
- Design and implement a RESTful API endpoint for fetching roles
- Use OrganizationGuard to handle organization context
- Ensure proper authentication and authorization checks
- Implement necessary database operations
- Provide appropriate error handling and response formatting

### Specific Requirements:
1. Implement GET /api/v1/organisations/roles endpoint
2. Use OrganizationGuard to extract and validate organization context
3. Ensure authentication using JWT tokens
4. Authorize users based on their permissions within the organization

## Success Response (200 OK)
```
{
  "status_code": 200, 
  "data": [
    { "id": "string", "name": "string", "description": "string" },
  ]
}
```

## TASKS
- [ ] Set up endpoint for fetching roles
- [ ] Implement OrganizationGuard
- [ ] Authentication and Authorization of roles endpoints
- [ ] Create database query to fetch roles efficiently
- [ ] Implement error handling for various scenarios
- [ ] Testing
  - Write unit tests for the role fetching endpoint
  - Write integration tests for the role fetching endpoint
- [ ] Documentation
  - Update API documentation with new endpoint details
  - Include examples of usage

**Comment by highb33kay** [comment]
In the update and fetch roles ticket, we have a description, don't we?

**Comment by Adebimpe12** [comment]
@highb33kay DEscription updated

**Comment by highb33kay** [comment]
Have you checked for duplicate?

**Comment by Adebimpe12** [comment]
@highb33kay Changed, thanks Chairman

**Comment by nedssoft** [comment]
I'm not exactly sure why this ticket is useful, what inspired this ticket?

**Comment by Adebimpe12** [comment]
Endpoint to retrieve roles 
Endpoint to create permissions 
Endpoint to retrieve permissions 
Endpoint to update user's role from implementing users roles and permissions

**Comment by Adebimpe12** [comment]
@nedssoft This one https://github.com/hngprojects/hng_boilerplate_nestjs/issues/259
