### ISSUE TITLE
[FEAT]: Implement Check Permissions Endpoint - Backend 

### ISSUE THREAD

**Issue by ZEED2468** [hngprojects/hng_boilerplate_nestjs#290]
Implement Check Permissions Endpoint with User Details

**Description:**
Develop a backend API endpoint that allows logged-in users to retrieve the permissions assigned to a specific user. This endpoint should be secure, validate user IDs, and handle various error scenarios. The response should include the user details.

**Acceptance Criteria:**

**Endpoints:**

**1. Check Permissions Endpoint:**
- **Method:** GET
- **URL:** `/api/v1/users/:userId/permissions`

**Request:**
- **Headers:**
  - `Authorization: Bearer <JWT_token>`

**Response:**
- **On success:**
  - **Status:** 200 OK
  - **Response Body:**
    ```json
    {
      "status_code": 200,
      "message": "Permissions fetched successfully",
      "data": {
        "user": {
          "id": "string",
          "first_name": "string"
          "last_name": "string"
          "email": "string",
          "created_at": "Date"
        },
        "permissions": [
          {"id": "1", "name": "create_user"},
          {"id": "3", "name": "delete_user"},
          {"id": "5", "name": "update_user"}
        ]
      }
    }
    ```

- **User Not Found:**
  - **Status:** 404 Not Found
  - **Response Body:**
    ```json
    {
      "status": "error",
      "message": "User not found",
      "status_code": 404
    }
    ```

- **Unauthorized Access:**
  - **Status:** 401 Unauthorized
  - **Response Body:**
    ```json
    {
      "status": "error",
      "message": "Unauthorized access",
      "status_code": 401
    }
    ```

**Validation:**
- Validate the JWT auth token.
- Ensure the `user-id` exists and is valid.
- Verify that the requesting user has the necessary permissions to access this endpoint.

**Purpose:**
To provide a secure and authenticated endpoint for retrieving the permissions assigned to a specific user, ensuring only authorized users can access this information, and to include user details in the response.

**Expected Outcome:**
A fully functional backend API endpoint that allows logged-in users to retrieve permissions assigned to a specific user, along with user details, with proper validation and error handling.

**Tasks:**

- [ ] Implement the GET endpoint to retrieve user permissions and details.
- [ ] Validate inputs and handle errors appropriately.
- [ ] Write unit tests for the endpoint to ensure it handles valid and invalid inputs correctly.

**Test Scenarios:**
1. **Successful permissions retrieval:** Verify that a logged-in user can retrieve permissions and user details with a valid user ID.
2. **User not found:** Verify that the endpoint returns a 404 status code when the user does not exist.
3. **Unauthorized access:** Verify that the endpoint returns a 401 status code when the user is not authorized to view the permissions.
4. **Validation error:** Verify that the endpoint returns a 400 status code when required parameters are missing or incorrectly formatted.

**Comment by highb33kay** [comment]
The user details should be returned as part of the response.

**Comment by ZEED2468** [comment]
done @highb33kay

**Comment by highb33kay** [comment]
@Shullyd7 boss
