### ISSUE TITLE
[FEAT]:Checkout Process - Frontend

### ISSUE THREAD

**Issue by King-Mikaelson** [hngprojects/hng_boilerplate_nestjs#37]
## Description

Develop the user interface to facilitate a secure and intuitive checkout process for users purchasing plans

### Automated Checkout System

- Design and implement an automated checkout process for purchasing plans.
- Ensure the UI is user-friendly and intuitive.

### User Preferences

- Allow users to select plans and input necessary details securely
- Validate user input on the client side before sending it to the backend.

### Payment Handling

- Display appropriate messages for successful transactions.
- Display user-friendly error messages for failed transactions.

### Purpose
To ensure users can complete their purchases smoothly and securely with minimal friction.

### Requirements	

- [x]  Develop the checkout UI to manage the process.
- [x]  Implement client-side logic for validation and transaction handling.

### Expected Outcome

- Users should be able to select a plan, input their details, and complete the purchase securely.
- Users should receive feedback on the success or failure of their transaction.

### Fetch Plans:

- Description: Retrieve a list of available plans for display.
- Endpoint: GET /api/plans

Response (Success):
```
{
  "plans": [
    {
      "id": "String",
      "name": "String",
      "description": "String",
      "price": "Number"
    }
  ]
}
```
Response (Error):

```
{
  "message": "Failed to fetch plans",
  "statusCode": 500
}
```

### Checkout Process

- Description: Send checkout details to the backend for processing.
- Endpoint: POST /api/checkout

Request Body:
```
{
  "userId": "String",
  "planId": "String",
  "paymentDetails": {
    "cardNumber": "String",
    "expiryDate": "String",
    "cvv": "String"
  }
}
```

Response (Success):

```
{
  "message": "Payment successful. Plan activated.",
  "transactionId": "String"
}
```

Response (Error):

```
{
  "message": "Payment failed",
  "statusCode": 400
}
```

## Tasks

- [ ]  Design and implement a responsive checkout page layout.
- [ ]  Add form fields for user information (name, email, address, payment details).
- [ ]  Display selected plan details and total cost.
- [ ]  Implement client-side validation for user inputs.
- [ ]  Display user-friendly error messages for validation issues.
- [ ]  Implement frontend logic to handle successful and failed transactions.
- [ ]  Write unit tests for the checkout UI components.

## Testing

1. Write unit tests for client-side validation logic.
2. Test various scenarios for user input validation.
3. Test the end-to-end flow from plan selection to payment completion.
4. Ensure the checkout UI works as expected for different user inputs.
