### ISSUE TITLE
[FEAT] Implement a Pricing Detailed Page - FRONTEND

### ISSUE THREAD

**Issue by Micah-Shallom** [hngprojects/hng_boilerplate_nestjs#38]
## **Description**
Develop the frontend logic and integrate backend APIs to create a detailed pricing page for each service.

### **Detailed Pricing Page:**
- Implement UI based on provided mockups.
- Fetch and display detailed pricing data from backend APIs.

### **User Experience:**
- Ensure the page is responsive across various devices and screen sizes.
- Design an intuitive and user-friendly interface.

### **Data Integration:**
- Retrieve detailed pricing information via API calls.
- Dynamically update the page content based on the retrieved data.

## **Purpose**
To provide users with detailed and up-to-date pricing information for each service, facilitating easy comparison and informed decision-making.

## **Requirements**
- Develop frontend components to display pricing information.
- Integrate with backend APIs to fetch pricing data.
- Ensure the page is fully responsive and maintains a high level of usability.

## **Expected Outcome**
Users will be able to access detailed pricing information for all services in a user-friendly and responsive manner. The page should dynamically display updated data retrieved from the backend.

#### **Fetch Pricing Data:**
- **Description:** Retrieve detailed pricing information for each service.
- **Endpoint:** `GET /api/pricing`
- **Response (Success):** `json`
  ```json
  {
    "services": [
      {
        "id": "String",
        "name": "String",
        "description": "String",
        "price": "Number"
      }
    ]
  }
  ```
- **Response (Error):** `json`
  ```json
  {
    "message": "Failed to fetch pricing data",
    "statusCode": 500
  }
  ```

## **Tasks**
- [ ] Develop UI components based on detailed mockups.
- [ ] Consume endpoint (`GET /api/pricing`) to fetch pricing data.
- [ ] Integrate frontend components with the backend API to display pricing information.
- [ ] Ensure the page layout is responsive and user-friendly.
- [ ] Implement error handling and display appropriate messages for API failures.

**Testing**
- [ ] Write unit tests for frontend components to ensure proper rendering and functionality.
- [ ] Write integration tests to verify API data fetching and display logic.
- [ ] Perform responsiveness testing to ensure the page layout adapts to different screen sizes.
- [ ] Conduct user experience testing to validate the usability of the page.

**Comment by markessien** [comment]
frontend
