### ISSUE TITLE
[FEAT]: Implement Email Messaging for Account Verification and Magic-Link Sign-Ins

### ISSUE THREAD

**Issue by abdielbytes** [hngprojects/hng_boilerplate_nestjs#44]
## Description
Implement a feature to send email notifications for account verification and magic-link sign-ins. This system will automate sending verification and magic link emails, as well as manage user preferences for these notifications.

### Acceptance Criteria

1. **Automated Email Notifications**:
   - Automatically send email notifications for new account registrations and magic link sign-ins using a single endpoint.

2. **User Preferences**:
   - Allow users to enable or disable specific email notifications.
   - Store user preferences securely in the database.

3. **Feedback and Error Handling**:
   - Display appropriate messages for successful email delivery.
   - Handle and display errors for failed email delivery.

### Purpose
The purpose of this feature is to:
- Ensure users receive timely email notifications for account verification and magic-link sign-ins.
- Allow users to manage their email notification preferences.
- Provide feedback to users on the status of email notifications.

### Requirements

1. **Email Notification System**:
   - [ ] Design and implement an automated email notification system for registrations and magic link sign-ins.
   - [ ] Use a centralized email service to handle sending emails.

2. **User Preferences**:
   - [ ] Provide UI for users to manage their email notification preferences.
   - [ ] Store preferences securely in the database.

3. **Email Delivery Feedback**:
   - [ ] Provide user feedback on successful or failed email actions.

4. **Email Templates**:
   - [ ] Implement email templates for user notifications, including verification links and magic links.

### Expected Outcome

- Users receive email notifications containing verification links and magic links in a timely manner.
- Users can manage their email notification preferences.
- The system displays appropriate messages for successful or failed email delivery.

### Implementation Steps

1. **Email Notification UI**:
   - Create a user interface for managing email notification preferences.

2. **Server-Side Validation and Handling**:
   - Implement server-side validation and handling for email notifications.
   - Ensure secure storage of user preferences in the database.

3. **Email Notification Preferences**:
   - Allow users to enable/disable specific email notifications.
   - Store these preferences securely in the database.

4. **User Feedback**:
   - Provide feedback to users on the status of email actions, including success and failure messages.

5. **Email Templates**:
   - Design and implement email templates for user notifications.

### Endpoint

**POST /api/v1/send-email**
- **Description**: Send an email for account verification or magic link sign-in based on the request type.
- **Request**:
  ```json
  {
    "email": "user@example.com",
    "type": "verification" // or "magic_link"
  }
  ```
- **Response**:
  - Status code: 200 OK
    ```json
    {
      "message": "Email sent successfully."
    }
    ```
  - Status code: 400 Bad Request
    ```json
    {
      "error": "Invalid request type or email."
    }
    ```

**Comment by markessien** [comment]
email service is centralised

**Comment by markessien** [comment]
An email sending ticket will never be approved
