### ISSUE TITLE
[FEAT]: API Endpoint to Fetch Single Role within an Organisation

### ISSUE THREAD

**Issue by davidolanrewaju** [hngprojects/hng_boilerplate_nestjs#461]
## Description
Develop and integrate an API endpoint to facilitate the fetching of roles within an organization

### Scope
- Design and implement a RESTful API endpoint for fetching a single role
- Use OrganizationGuard to handle organization context
- Ensure proper authentication and authorization checks
- Validate input data and handle edge cases
- Implement necessary database operations
- Provide appropriate error handling and response formatting

### Specific Requirements:
1. Implement GET /api/v1/organisations/roles/{role-id} endpoint
2. Use OrganizationGuard to extract and validate organization context
3. Ensure authentication using JWT tokens
4. Authorize users based on their permissions within the organization
5. Validate the role ID format
6. Fetch role details including associated permissions
7. Handle cases where the role or organization does not exist

### Path Parameters
- ```role-id```: string, required (UUID format)

### Success Response (200 OK)
```
{
  "status_code": 200,
  "data": { "id": "string",
    "name": "string",
    "description": "string",
    "permissions": [
      {
        "id": "string",
        "category": "string",
        "permission_list": { "can_view_transactions": boolean, "can_view_refunds": boolean, "can_edit_transactions": boolean }
      }
    ]
  } 
}
```

### Error Responses
**400 Bad Request**
```
{
  "status_code": 400,
  "error": "Bad Request",
  "message": "Invalid role ID format"
}
```
**404 Not Found (Role)**
```
{
  "status_code": 404,
  "error": "Not Found",
  "message": "The role with ID ${id} does not exist"
}
```

## TASKS
- [ ] Set up endpoint for fetching a single role
- [ ] Implement OrganizationGuard
- [ ] Authentication and Authorization of roles/{role-id} endpoint
- [ ] Validate role ID format
- [ ] Implement database query to fetch role details efficiently, including permissions
- [ ] Implement error handling for various scenarios (invalid ID, non-existent role)
- [ ] Testing
  - Write unit tests for the single role fetching endpoint
  - Write integration tests for the single role fetching endpoint
  - Test error scenarios (invalid ID, non-existent role, non-existent organization)
- [ ] Documentation
  - Update API documentation with new endpoint details
  - Include examples of successful and error responses
