### ISSUE TITLE
[FEAT]: Get All Email Templates

### ISSUE THREAD

**Issue by trevorjob** [hngprojects/hng_boilerplate_nestjs#463]
## Description

Develop an API endpoint to retrieve all email templates.

## Acceptance Criteria

- The endpoint should be accessible at ``` api/v1/email/templates ```

- The endpoint should accept HTTP GET requests.

- The endpoint should be secured to ensure that only authenticated users can retrieve email templates.

- Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.

- Requests to the endpoint must include a valid authentication token in the Authorization header: Authorization: Bearer <token>

- The endpoint should return a list of email templates with their names and content.

## Request

- HTTP Method: GET

- Endpoint: /api/v1/email-templates

- **Request Headers:**
```python
{
  "Authorization": "Bearer <token>"
}
```
- **Response**

- On Successful Retrieval

- Status Code: 200

- **Response Body:**
```python
{
  "status_code": 200,
  "status": true,
   "data": {
         "templates": {
             "waitlist": "string"
              "confirm": "string"
              "newsletter": "string"
               // More templates...
           }
     }
}
```

- If the User is Not Authenticated

- Status Code: 401 Unauthorized

- **Response Body:**
```python
{
  "success": false,
  "status_code": 401,
  "message": "Not authenticated"
}
```
## Purpose

- Provides a backend service for users to retrieve all available email templates.

## Requirements

- Develop server-side logic to retrieve email templates from the filesystem or database.

- Ensure that only authenticated users can access this endpoint.

## Expected Outcome

- The API endpoint allows authenticated users to retrieve all email templates with appropriate validation and authentication.

## Tasks

- [ ] Create an endpoint GET /api/v1/email-templates to retrieve all email templates.

- [ ] Implement server-side logic to handle successful and failed retrieval requests.

- [ ] Ensure the user is authenticated before allowing access to the email templates.

- [ ] Write unit tests for retrieving email templates.

- [ ] Write integration tests for retrieving email templates.

- [ ] Perform security testing to ensure data protection and compliance.

## Testing

- [ ] Write unit tests for backend validation.

- [ ] Write integration tests for the end-to-end email template retrieval process.

- [ ] Perform security testing to ensure data protection and compliance.

- [ ] Test various scenarios for retrieving email templates, including valid and invalid authentication tokens.

**Comment by ezeanyimhenry** [comment]
This issue is a duplicate of [this previously approved issue](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/234)
