### ISSUE TITLE
[FEAT] Subscription Renewal Reminder Email

### ISSUE THREAD

**Issue by Reliable25** [hngprojects/hng_boilerplate_nestjs#54]
## Description
This feature involves creating an endpoint to generate and send subscription renewal reminder emails. The endpoint will allow the system to notify users about their upcoming subscription renewals.

## Acceptance Criteria
- The system can generate personalized renewal reminder emails.
- Emails include the subscriber's name, renewal date, and subscription details.
- The endpoint should handle different subscription types and prices.
- Proper error handling and validation should be implemented.

### Purpose
- This feature aims to remind users when it's time to renew their subscriptions. It helps keep customers using our service and encourages them to stay subscribed.
### Requirements	
- Implement a RESTful endpoint for generating renewal reminder emails.
- Use appropriate request body parameters to customize the email content.
- Integrate with the existing email service to send the reminders.
- Ensure the endpoint adheres to best practices for API design and security.
- Write unit and integration tests to validate the functionality.

### Endpoint
**URL**
```http
v1/api/subscriptions/send-renewal-reminder
```
METHOD:
```http
POST
```

### Request Body Parameters:
- subscriberName (required): The name of the subscriber.
- subscriberEmail (required): The email address of the subscriber.
- renewalDate (required): The date when the subscription will renew.
- subscriptionPlan (required): Details of the subscription plan.
- price (required): The price of the subscription.

### Example Request
```json
{
  "subscriberName": "John Doe",
  "subscriberEmail": "johndoe@example.com",
  "renewalDate": "2024-09-17",
  "subscriptionPlan": "Bi-monthly",
  "price": 20.99
}
```
### Response:
**Success Response (json)**
```json
{
  "success": true,
  "message": "Renewal reminder email sent successfully",
  "statusCode": 200
}
```
**Validation Error Response (json)**
```json
{
  "success": false,
  "errors": [
    {
      "parameter": "subscriberName",
      "message": "Subscriber name is required"
    }
  ],
  "statusCode": 422
}
```
**Error Response (json)**
```json
{
  "success": false,
  "message": "Failed to send renewal reminder email",
  "statusCode": 500
}
```
### Task:

- [ ] Design the subscription renewal reminder email endpoint.
- [ ]  Implement request body parameters for subscriber details and subscription information.
- [ ]  Integrate the endpoint with the existing email service.
- [ ]  Implement error handling and validation for the request.
- [ ]  Write unit tests for the email generation functionality.
- [ ]  Write integration tests for the endpoint.
- [ ]  Document the API endpoint and usage.
### Expected Outcome
- A functional endpoint that generates and sends personalized subscription renewal reminder emails.
- The system can handle various subscription types and pricing models.
- Emails are sent successfully and contain accurate information.
- The endpoint handles errors gracefully and provides meaningful feedback.

**Comment by markessien** [comment]
this is not how this works

**Comment by Reliable25** [comment]
Updated sir
