### ISSUE TITLE
[FEAT] Implement API Endpoints for Creating Subscription Plans

### ISSUE THREAD

**Issue by davidolanrewaju** [hngprojects/hng_boilerplate_nestjs#55]
## Description
Develop backend support to create subscription plans. This feature will enable admin to create various plans.

## Acceptance Criteria
- Subscription plans can be created through the API.
- All unit and integration tests pass successfully.
- Both API and user documentation are updated to reflect the new subscription plan feature.

### Error Handling:
- Log errors for invalid requests.
- Display clear error messages for invalid inputs.

### Security Measures:
- Use HTTPS for secure data transmission.
- Validate user input on the server side.

## Purpose
To provide admin with the ability to create different subscription plans.

### Requirements
- [ ] Admin must be authenticated and authorized.
- [ ] Develop server side logic to add subscription plans to database.

### Expected Outcome
1. The backend should handle subscription plan creation efficiently.
2. The system should log responses and errors properly

### DB Schema

![349881877-9cdff051-4898-4951-ba4e-118c1de3d29c](https://github.com/user-attachments/assets/e79cc0ab-5e08-4e2f-bdaa-816470568e7d)

## Endpoints
- Endpoint: ``` HTTP POST /api/v1/plans ```

- #### Request Body:
 ```
{
 "name": "String",
  "description": "String",
  "price": Integer,
  "duration": "String"
  "features": ["Feature 1", "Feature 2"]
}
```

- #### Success Response: Create Subscription Plan 
```
HTTP/1.1 200 OK
Content-Type: application/json

 {
   data: { 
     "id": "String",
     "name": "String",
     "description": "String",
     "price": Integer,
     "duration": "String"
     "features": ["Feature 1", "Feature 2"]
  },
  status: 200,
}
```

- #### Error Response: Unauthorized Access
```
HTTP/1.1 403 Forbidden
Content-Type: application/json

{
  "status": 403,
  "error": "User is not authorized to create subscription plans."
}
```

- #### Error Response: Subscription Plan already exists
```
HTTP/1.1 400 Subscription plan already exists
Content-Type: application/json

{
  "status": 400,
  "error": "subscription plan already exists."
}
```

### Tasks
- [ ] Create an endpoint (HTTP POST /api/v1/plans) to create new subscription plans.
- [ ] Write unit tests for the endpoint.
- [ ] Write integration tests for the plan creation process.

### Testing
- Write unit tests for authorization and fetching products.
- Write integration tests for the end-to-end process.
- Perform security testing to ensure data protection and compliance.

**Comment by markessien** [comment]
fetching products is not a super admin matter, and so called top products is just a filter

**Comment by davidolanrewaju** [comment]
@buka4rill

**Comment by davidolanrewaju** [comment]
### Team members working on this issue include:

- [Adewale Kujore](https://github.com/Adewale66)- Java
- [Anieka](https://github.com/Iamaniekan) - Python
- [Doris Ifeoma](https://github.com/dorisjenny27) - C#

#### P.S: I couldn't assign them directly to the repo since they don't have access to the repo. Also, the names signify their slack ids

**Comment by Shullyd7** [comment]
Specify status codes in all the response payload

**Comment by thenoblet** [comment]
Hello everyone @markessien, @buka4rill, @davidolanrewaju 

I’ve created a new issue [Implement API Endpoints for READ/GET and DELETE Subscription Plans](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/231l) that complements this issue. While this issue focuses on creating subscription plans, my issue addresses the endpoints required for **reading**, **getting**, and **deleting** those subscription plans.

The goal is to complete the suite of CRUD operations for subscription plans, ensuring a comprehensive API that covers all necessary interactions with subscription data. Please refer to the new issue  #231 for details on the additional endpoints needed.
