### ISSUE TITLE
[FEAT]: API Endpoint for Creating Roles within an Organisation

### ISSUE THREAD

**Issue by SundayMba** [hngprojects/hng_boilerplate_nestjs#56]
## Description 
Develop and integrate an API endpoint to facilitate the creation of roles within an organization

### Scope:
- Design and implement a RESTful API endpoint for role creation
- Use OrganizationGuard to handle organization context
- Ensure proper authentication and authorization checks
- Validate input data and handle edge cases
- Implement necessary database operations
- Provide appropriate error handling and response formatting 

### Specific Requirements: 
- Implement `POST /api/v1/organisations/roles` endpoint
- Use OrganizationGuard to extract and validate organization context
- Ensure authentication using JWT tokens
- Authorize users based on their permissions within the organization
- Validate input:
      - `name`: required, unique within org, max 50 characters
      - `description`: optional, max 200 characters
      - `permissions`: array of valid permission IDs
- Create role in database if all checks pass

## Request Body:
```
{ 
  "name": "string",
  "description": "string",
}
```

## Success Response (201 Created)
```
{ 
  "id": "string", 
  "name": "string", 
  "description": "string",
  "message": "Role created successfully" 
}
```

### 400 Bad Request (Invalid Input)
```
{
  "status_code": 400,
  "error": "Invalid input",
  "message": "Detailed error message"
}
```

### 409 Conflict (Duplicate Role)
```
{
  "status_code": 409,
  "error": "Conflict",
  "message": "A role with this name already exists in the organization"
}
```

## Tasks

- [ ] Set up endpoint for role creation
- [ ] Implement OrganizationGuard
- [ ] Authentication and Authorization of `roles` endpoints
- [ ] Validate all input required for creating roles
- [ ] Implement the required logic and database schema required for role creation
- [ ] Create custom exception to handle various error scenarios
- [ ] Testing
  - Write unit tests for the role creation endpoint
  - Write integration tests for the role creation  endpoint
  - Write tests for all instances of creating roles
- [ ] Documentation

**Comment by markessien** [comment]
roles is not just for superadmin, they are tied to the org

**Comment by SundayMba** [comment]
noted. i will add the feature now.

**Comment by SundayMba** [comment]
fix: feature implemented.

**Comment by AzubuikeKevin** [comment]
Okat

**Comment by Jude-Ugoo** [comment]
@SundayMba I am on your team

**Comment by urizennnn** [comment]
@SundayMba on your team too

**Comment by codelikesuraj** [comment]
@SundayMba I'm on your team

**Comment by buka4rill** [comment]
You need something like this

![CleanShot 2024-07-17 at 18 10 59](https://github.com/user-attachments/assets/d53ad0b1-b1e2-4b17-a70b-b1fe3869bc3d)

**Comment by SundayMba** [comment]
fix: updated to include the features you highlighted. @buka4rill

**Comment by NdubuisiJr** [comment]
@SundayMba  This looks good. Except in your `permissions` key. Is that the `permission_Id`? Because existing permissions is need for creating roles.

**Comment by SundayMba** [comment]
yes, it is the permission_ids. i have effected it now. thanks so much @NdubuisiJr

**Comment by pesova** [comment]
@SundayMba either remove the role_id here or put it inside data
{
  "message": "Role created successfully.",
  "role_id": "String"
}

**Comment by pesova** [comment]
add status code to the above as well

**Comment by SundayMba** [comment]
okay done, i prefer removing it, i have also added the status code. @pesova
