### ISSUE TITLE
[FEAT] Implement Sign-In with Token Authentication

### ISSUE THREAD

**Issue by alexindevs** [hngprojects/hng_boilerplate_nestjs#58]
## Description
Implement a sign-in functionality where users can log in using a 6-digit token sent to their email. 

## Acceptance Criteria
- **Request Token Endpoint:**
    - Accepts an email address in the request body.
    - Checks that the user has a valid account.
    - Generates a 6-digit code.
    - Sends the generated code to the provided email.
    - Responds with a message indicating the code has been sent.
    - Handles invalid email input by responding with a 400 Bad Request status.

- **Verify Token Endpoint:**
    - Accepts an email address and 6-digit code in the request body.
    - Verifies the code and email combination.
    - Responds with a session token (e.g., JWT) upon successful verification.
    - Handles invalid token or email input by responding with a 401 Unauthorized status.

- **Token Management:**
  - Ensure the 6-digit code has an expiry time (e.g., 5 minutes).
  - Securely store the generated code until it expires or is used.
  - Invalidate the code after successful verification or expiration.
 
### Purpose
 Instead of requiring users to remember and manage complex passwords, this feature leverages a one-time 6-digit code sent to the user's email for authentication.

### Expected Outcome
The user should be able to sign in to their account successfully and receive a JWT authentication token.

### Endpoints

**Request Sign-In Token:**
- **Description:** Generate and send a 6-digit sign-in token to the user's email.
- **Endpoint:** `POST /auth/request-token`
- **Request Body:**
  ```json
  {
    "email": "user@example.com"
  }
  ```
- **Response (Success):**
  ```json
  {
    "message": "Sign-in token sent to email",
    "statusCode": 200
  }
  ```
- **Response (Error):**
  ```json
  {
    "message": "Failed to send sign-in token",
    "statusCode": 400
  }
  ```

**Verify Sign-In Token:**
- **Description:** Verify the 6-digit sign-in token and log in the user.
- **Endpoint:** `POST /auth/verify-signin-token`
- **Request Body:**
  ```json
  {
    "email": "user@example.com",
    "token": "123456"
  }
  ```
- **Response (Success):**
  ```json
  {
    "message": "Sign-in successful",
    "token": "JWT token here",
    "statusCode": 200
  }
  ```
- **Response (Error):**
  ```json
  {
    "message": "Invalid token or email",
    "statusCode": 401
  }
  ```

### Tasks
- [ ] Create the `POST /auth/request-token` endpoint.
- [ ] Implement logic to generate a 6-digit token.
- [ ] Integrate email service to send the token.
- [ ] Handle invalid email input.
- [ ] Write unit tests for the `POST /auth/request-token` endpoint.

- [ ] Create the `POST /auth/verify-signin-token` endpoint.
- [ ] Implement logic to verify the token and email combination.
- [ ] Generate a session token (e.g., JWT) upon successful verification.
- [ ] Handle invalid token or email input.
- [ ] Write unit tests for the `POST /auth/verify-signin-token` endpoint.
- [ ] Set token expiry time (e.g., 20 minutes).
- [ ] Securely store and manage tokens.

### Testing
- Write unit tests for both the request token and verify token endpoints.
- Include integration tests to verify the end-to-end functionality.

**Comment by markessien** [comment]
Does not make sense to have admin crud separate
