### ISSUE TITLE
[FEAT]: Remove Member From Organization

### ISSUE THREAD

**Issue by Goldyn19** [hngprojects/hng_boilerplate_nestjs#61]
## Description
Develop an API endpoint that removes a user from an organization.

### Authentication Middleware
- Implement middleware to ensure the user (org admin) is authenticated using JWT.
- If authentication fails, return a 401 Unauthorized status code.
- If authenticated, proceed with the request.

### Authorization
- Implement an authorization check to ensure that only the organization's owner (org admin) has the ability to remove users.

### API Endpoint Implementation:
- The endpoint should be accessible at `/api/v1/organizations/{org_id}/users/{user_id}`.
- The endpoint should accept http DELETE request.

### Remove User from Organization:
- Upon successful validation, the API should remove the user to the specified organization.

### Response:
- On success, the API should return a `200 with content` status code with the success message.
- On failure, the API should return a 400 Bad Request status code with appropriate error messages.
  
-   **Response (Success):**
  ```
{
  "status": "success",
  "message": "user deleted successfully",
  "status_code": 200
}
```
    
-   **Response (Error):**
    
  ```     
{
  "status": "forbidden",
  "message": "user not found",
  "status_code": 404
}
```

## Unauthenticated Error Message
```json
{
  "status": "Unauthorized",
  "message": "User not authenticated",
  "status_code": 401
}
```

## Unauthorized Error Message
```json
{
  "status": "Forbidden",
  "message": "Only admin can remove users",
  "status_code": 403
}
```

## Purpose
Provide a backend service that allows organizations' owners to remove users from organizations, ensuring proper authentication, authorization, and validation.

## Requirements
- Implement middleware for JWT authentication.
- Implement an authorization check to ensure that only the organization's owner has the ability to remove users.
- Develop server-side logic to remove a user from an existing organization.

## Expected Outcome
The API endpoint allows users (organization owners) remove users(members) from their organization with appropriate authentication and authorization

## Task 
- [ ] Create the endpoint HTTP DELETE `/api/v1/organizations/{org_id}/users/{user_id}` to remove a user from an organization.
- [ ] Implement authentication middleware to validate JWT tokens.
- [ ] Implement an authorization check to ensure that only the organization's owner has the ability to add users.
- [ ] Validate the request param {orgId} and {userId}
- [ ] Write unit tests for all scenarios, including successful removal of user from organization, validation errors, and authentication/authorization checks.
- [ ] Perform security testing to ensure data protection and compliance.

## Testing
- Write unit tests for successful removal of organization members.
- Write unit tests for fields validation.
- Write unit tests for bad client requests.
- Write unit tests for authentication and authorization checks.
- Perform security testing to ensure data protection and compliance.

**Comment by markessien** [comment]
Tickt description is kind of vague

**Comment by markessien** [comment]
Your endpoint is wrong

**Comment by NdubuisiJr** [comment]
@desgee you can return 200 status code for a `DELETE` API. Also, following the route versioning rule.

**Comment by desgee** [comment]
@NdubuisiJr This is acknowledged, thank you sir. The status code is 200.
