### ISSUE TITLE
[FEAT]: Third Party App Integration -Backend

### ISSUE THREAD

**Issue by Goldyn19** [hngprojects/hng_boilerplate_nestjs#62]
### Description
Develop the backend logic to integrate third-party applications (Zoom, Teams, Slack, Dropbox, OneDrive, etc.) into the organization's workflow, enabling the activation and deactivation of these apps efficiently.
#### Third-Party App Integration:
-   Implement server-side logic to handle the integration of third-party applications.
-   Develop endpoints to activate and deactivate third-party applications.
#### User Preferences:
-   Store integration details securely in the database.
-   Handle user-specific configurations and preferences related to each application.
#### Activation/Deactivation Handling:
-   Log successful activations and deactivations.
-   Implement retry mechanisms for failed activations/deactivations.
#### Security Measures:
-  Use HTTPS for secure data transmission.
-  Validate user input on the server side.
-  Encrypt sensitive data such as API tokens and user credentials.
### Purpose
To enhance workflow efficiency by enabling seamless integration with third-party applications, allowing users to activate and deactivate these apps securely and efficiently.
### Requirements
- Develop server-side logic to integrate third-party applications.
- Securely store integration details in the database.
- Ensure compliance with security standards for handling sensitive information.
### Expected Outcome
- The backend should handle the activation and deactivation of third-party applications securely and efficiently.
- The system should log activations/deactivations and handle errors appropriately.
#### Fetch Apps:
**Description:** Provide a list of available third-party applications to the frontend.
**Endpoint:** GET /api/apps
**Response (Success):**
```json
{
  "apps": [
    {
      "id": "String",
      "name": "String",
      "description": "String",
      "status": "String"  // e.g., "active" or "inactive"
    }
  ]
}
```
**Response (Error):**
```json
{
  "message": "Failed to fetch apps",
  "statusCode": 500
}
```
#### Activate App:
**Description:** Activate a selected third-party application.
**Endpoint:** POST /api/apps/activate
**Request Body:**
```json
{
  "userId": "String",
  "appId": "String"
}
```
**Response (Success):**
```json
{
  "message": "App activated successfully.",
  "transactionId": "String"
}
```
**Response (Error):**
```json
{
  "message": "App activation failed",
  "statusCode": 400
}
```
#### Deactivate App:
**Description:** Deactivate a selected third-party application.
**Endpoint:** POST /api/apps/deactivate
**Request Body:**
```json
{
  "userId": "String",
  "appId": "String"
}
```
**Response (Success):**
```json
{
  "message": "App deactivated successfully.",
  "transactionId": "String"
}
```
**Response (Error):**
```json
{
  "message": "App deactivation failed",
  "statusCode": 400
}
```
### Tasks
-  [ ] Create an endpoint (GET /apps) to fetch available third-party applications.
-  [ ] Create endpoints (POST /apps/activate, POST /apps/deactivate) to handle the activation and deactivation of applications.
-  [ ] Validate user input on the server side.
-  [ ] Integrate with third-party APIs (e.g., Zoom, Teams, Slack, Dropbox, OneDrive) to handle app activations and deactivations.
-  [ ] Implement server-side logic to handle successful and failed activations/deactivations.
-  [ ] Ensure all sensitive data is encrypted and secure.
-  [ ] Implement logging for errors and activation/deactivation attempts.
-  [ ] Write unit tests for the activation and deactivation endpoints.
-  [ ] Write integration tests for third-party API integrations.
### Testing
-   Write unit tests for backend validation and transaction handling.
-   Write integration tests for the end-to-end activation/deactivation process.
-   Perform security testing to ensure data protection and compliance.
-   Test various scenarios for app activations and deactivations (e.g., successful, failed, retry).

**Comment by markessien** [comment]
This is not a feature we will be doing in this app
