### ISSUE TITLE
[FEAT]: Modify Members -Backend

### ISSUE THREAD

**Issue by Goldyn19** [hngprojects/hng_boilerplate_nestjs#63]
### Issue: Implement API To Change Organization members  Role

**Acceptance Criteria:**

-Authentication
    -  Only users with sufficient permissions (e.g., team admins) can change organization member roles.
-   Error Handling:
    -   Log errors for invalid requests.
    -   Display clear error messages for invalid inputs.
-   Security Measures:
    -   Use HTTPS for secure data transmission.
    -   Validate user input on the server side.

**Purpose:** To change the role of every organization member and assign privileges

**Requirements:**

-   Develop server-side logic to change organization member roles.
-   Securely store user status details in the database.
-   Ensure compliance with security standards for handling user information.

**Expected Outcome:**

-   The backend should change member role securely and efficiently.
-   The system should log errors and handle invalid requests appropriately.

**Endpoints:**

**Change User Role:**

-   **Description:** Change members role.
-   **Endpoint:** `PUT /api/teams/{teamId}/members/{memberId}/role`
-   **Request Body:**
  ```
{
  "newRole": "string"
}
```
-   **Response (Success):**
   
  ```
{
  "message": "Team member role updated successfully",
  "teamId": "string",
  "memberId": "string",
  "newRole": "string"
}
```
    
-   **Response (Error):**
    
  ```     
  {
  "error": "message"
 "error code": "code"
}
```

**Tasks:**

- [ ]  Create an endpoint `PUT /api/teams/{teamId}/members/{memberId}/role` to fetch users based on search and filter criteria.
- [ ] Validate user input on the server side.
- [ ] Implement server-side logic to handle successful and failed change user role requests.
- [ ] Ensure all sensitive data is encrypted and secure.
- [ ] Implement logging for errors and change user role attempts.
- [ ] Write unit tests for the change user role endpoint.
- [ ] Write integration tests for the  change user role logic.
- [ ] Perform security testing to ensure data protection and compliance.

**Testing:**

-   Write unit tests for backend validation and change user role handling.
-   Write integration tests for the end-to-end change user role process.
-   Perform security testing to ensure data protection and compliance.
-   Test various scenarios for change user role.

**Comment by buka4rill** [comment]
Remember to version your endpoint

**Comment by NdubuisiJr** [comment]
@Goldyn19 follow the API versioning rule
