### ISSUE TITLE
[FEAT]: Filter Users -Backend

### ISSUE THREAD

**Issue by Goldyn19** [hngprojects/hng_boilerplate_nestjs#66]
### Issue: Implement Search and Filtering for Users

**Acceptance Criteria:**

-   Automated Search and Filtering System:
    -   Implement server-side logic to handle searching users by email or name.
    -   Implement server-side logic to handle filtering users by their status (members, suspended, left workspace).
-   User Preferences:
    -   Store user status details securely in the database.
    -   Handle user-specific configurations and preferences related to the search and filtering process.
-   Error Handling:
    -   Log errors for invalid search/filter requests.
    -   Display clear error messages for invalid inputs.
-   Security Measures:
    -   Use HTTPS for secure data transmission.
    -   Validate user input on the server side.

**Purpose:** To search and filter users securely and efficiently, ensuring accurate and safe user management.

**Requirements:**

-   Develop server-side logic to handle user search and filtering.
-   Securely store user status details in the database.
-   Ensure compliance with security standards for handling user information.

**Expected Outcome:**

-   The backend should handle user search and filtering securely and efficiently.
-   The system should log errors and handle invalid requests appropriately.

**Endpoints:**

**Fetch Users:**

-   **Description:** Provide a list of users based on search and filter criteria.
-   **Endpoint:** GET /api/users
-   **Request Parameters:**
     ```
     "email" (optional): "string"
     "name" (optional): "string"
     "status" (optional): "string (values: "members", "suspended", "left")"
     ```
-   **Response (Success):**
    
  
    
    ```
      {
        "id": "String",
        "email": "String",
        "name": "String",
        "role": "String",
        "signup_type": "String",
        "is_active": true,
        "is_verified": true,
        "created_at": "Date",
        "updated_at": "Date",
        "last_login_at": "Date",
        "status": "String"
      }
    ```
    
-   **Response (Error):**
    
     ```
      {
      "message": "Failed to fetch users",
      "statusCode": 500
    }
    ```

    

**Tasks:**

- [ ]  Create an endpoint `GET /api/users` to fetch users based on search and filter criteria.
- [ ] Validate user input on the server side.
- [ ] Implement server-side logic to handle successful and failed search/filter requests.
- [ ] Ensure all sensitive data is encrypted and secure.
- [ ] Implement logging for errors and search/filter attempts.
- [ ] Write unit tests for the user search and filter endpoint.
- [ ] Write integration tests for the search and filter logic.
- [ ] Perform security testing to ensure data protection and compliance.

**Testing:**

-   Write unit tests for backend validation and search/filter handling.
-   Write integration tests for the end-to-end search/filter process.
-   Perform security testing to ensure data protection and compliance.
-   Test various scenarios for user search/filter (e.g., valid email, invalid email, valid status, invalid status).

**Comment by markessien** [comment]
It's unclear if this is filter only, or if this is the general use retrieval api
