### ISSUE TITLE
[FEAT]: Implement Backend API for Squeeze Page - Backend

### ISSUE THREAD

**Issue by Fifetoyi** [hngprojects/hng_boilerplate_nestjs#80]
## Description:
Develop the API endpoint for the Squeeze Page.

## Purpose:
Provides a backend service that allows us collect the user email, store in the database and send a template to the user.

## Requirements:

- [ ] Develop a RESTful API endpoint to handle POST requests.
- [ ] Validate and verify incoming user data.
- [ ] Store user information securely in the database.
- [ ] Return appropriate response.
- [ ] Handle errors and return appropriate status codes.
- [ ] Send template to a specified email address using an email service (e.g., SendGrid, SMTP).

## Acceptance Criteria:
- The page should be accessible at `/api/v1/squeeze`.
- The endpoint should accept HTTP POST requests.

### Squeeze Form Submission:

- Endpoint: POST `/api/v1/squeeze`
- Request Body: 
```
{
  "email": "user@example.com",
  "first_name": "John",
  "last_name": "Doe",
  "phone": "08098761234",
  "location": "Lagos, Nigeria",
  "job_title": "Software Engineer",
  "company": "X-Corp",
  "interests": ["Web Development", "Cloud Computing"],
  "referral_source": "LinkedIn"
}
```
- Validation: Ensure all fields are required and the email is in the correct format.
- Response (Success): 
```
{
  "message": "Your request has been received. You will get a template shortly."
}
```
- Response (Error): 
```
{
  "message": "Failed to submit your request",
  "status_code": 400
}
```
## Tasks:

- [ ] Create an endpoint (POST `/api/v1/squeeze`) to handle contact form submissions.
- [ ] Validate user input on the server side.
- [ ] Securely store user information in the database.
- [ ] Implement error handling and return appropriate status codes.
- [ ] Write unit tests for contact form submission and data validation.
- [ ] Write integration tests for confirmation of requests.

## Testing:

- Write unit tests for backend validation and data handling.
- Write integration tests for the end-to-end contact form submission process.
- Perform security testing to ensure data protection and compliance.
- Test various scenarios for form submissions (e.g., successful, invalid data, server errors).

## Expected Outcome:
A secure and efficient API endpoint that can receive user email, store it in the database, and confirm the user's request.
The API endpoint allows users to submit a request via the "Squeeze" form, and ensures the template is sent to the appropriate email address.

## Labels
feature

**Comment by markessien** [comment]
These are multiple tickets, split them up as separate tickets

**Comment by markessien** [comment]
A squeeze page gather far more than the users email

**Comment by Fifetoyi** [comment]
I have updated the endpoint. The figma file only has provision for names and email @markessien

**Comment by devffery** [comment]
@buka4rill

**Comment by markessien** [comment]
Not enough

**Comment by coderoyalty** [comment]
@markessien what else could a squeeze page gather?

**Comment by coderoyalty** [comment]
@Fifetoyi 

Here's an example:

```json
{
  "email": "user@example.com",
  "first_name": "John",
  "last_name": "Doe",
  "phone": "123-456-7890",
  "location": "Lagos, Nigeria",
  "job_title": "Software Engineer",
  "company": "X-Corp",
  "interests": ["Web Development", "Cloud Computing"],
  "referral_source": "LinkedIn"
}
```
This should be enough

**Comment by Fifetoyi** [comment]
@markessien added more details for the squeeze page

**Comment by Fifetoyi** [comment]
Can we get a second approval on this please? @buka4rill

**Comment by Shullyd7** [comment]
Add versioning to your endpoints and maintain the snake case

**Comment by Fifetoyi** [comment]
versioning and snake case implemented @Shullyd7

**Comment by mjoghenemaega** [comment]
@coderoyalty  and @Fifetoyi   the comment mark made above "These are multiple tickets, split them up as separate tickets" .... did you guys initially add a get or put request .... if yes .. hope i am free to create another ticket  for get ?
