### ISSUE TITLE
[FEAT] Update product detail - BACKEND

### ISSUE THREAD

**Issue by trini7y** [hngprojects/hng_boilerplate_nestjs#86]
## Description
Implement a functionality to update product details

## Acceptance Criteria

* The endpoint should be accessible at ```/api/product/:productId```.
* The endpoint should accept HTTP ```PUT``` requests.
* The endpoint should be secured to ensure that only authenticated users can update product details.
* Proper authentication mechanisms should be implemented e.g JWT.
* Requests to the endpoint must include a valid authentication token in the Authorization header. ```Authorization: Bearer <token>```

* ***Request body***

``` python
   {
      product_name: "product name",
      price: 5000,
      description: "Product description"
   }

```
* ***Response (Success):***
* On a successful updating of product detail, the API should return a 201 Created status code.
* The response body should contain the updated product.
```python
   {
      id: 3,
      message: "Product details for updated successfully",
      product_name: "product name",
      price: 5000,
      description: "Product description"
   }
```

* ***Validation***
- If any required field is missing or invalid, the API should return a 400 Bad Request status code with appropriate validation error messages.

```python
{
  statusCode: 400,
  message: ["name must be a string", "price must be a positive number"],
  error: "Bad Request"
}
```

### Purpose
To allow users to edit a particular product detail

### Requirements	

* Develop server-side logic to update
* Securely store product details in the database.
* Ensure compliance with security standards for handling user information.

### Expected Outcome
A user should be able to click on a button and a modal pop-up to update product details and get appropriate feedback responses.

### Task

- [ ]  Create an endpoint ```PUT /api/product/:productId``` to update an existing product.
- [ ]  Implement server-side logic to handle successful and failed updates of product details.
- [ ]  Write unit tests for updating product details.
- [ ]  Write integration tests for updating product details.
- [ ]  Ensure the user has the proper permissions to update the product details.

### Test

- Write unit tests for frontend components to ensure proper rendering and functionality.
- Write integration tests to verify API data fetching and display logic.
- Perform responsiveness testing to ensure the page layout adapts to different screen sizes.
- Conduct user experience testing to validate the usability of the page.
- 
- ###

**Comment by markessien** [comment]
This is a backend repo

**Comment by trini7y** [comment]
Oh! Let me replace for the frontend repo, thank you
