### ISSUE TITLE
[FEAT] Add Products API - BACKEND

### ISSUE THREAD

**Issue by DevUju** [hngprojects/hng_boilerplate_nestjs#87]
## Description
Develop an API endpoint to add new products with input validation

## Acceptance Criteria
* The endpoint should be accessible at ``` api/products```.
* The endpoint should accept HTTP ```POST``` requests.
* The endpoint should be secured to ensure that only authenticated users can add new products.
* Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header. ```Authorization: Bearer <token>```
* ***Request Body***
```python
{
  product_name: "Product Name",
  price: 550.0,
  description: "Product Description"
}
```
* ***Response***

- On a successful addition of a new product, the API should return a 201 Created status code.
- The response body should contain the newly created product details, including the product ID.
 ```python
{
  id: 1,
  product_name: "Product Name",
  price: 550.0,
  description: "Product Description"
}
```
* ***Validation***
- If any required field is missing or invalid, the API should return a 400 Bad Request status code with appropriate validation error messages.

```python
{
  statusCode: 400,
  message: ["name must be a string", "price must be a positive number"],
  error: "Bad Request"
}
```

### Purpose
Provides a backend service which allows users to add new products to the system

### Requirements	

* Develop server-side logic to add new product
* Securely store product details in the database.
* Ensure compliance with security standards for handling user information.

### Expected Outcome
*  API endpoint allows adding of new products with appropriate validation

###Task 

- [ ]  Create an endpoint ```POST /api/product``` to add new product.
- [ ]  Implement server-side logic to handle successful and failed add product request.
- [ ]  Ensure the user has the proper permissions to add product
- [ ]  Write unit tests for the adding new product.
- [ ]  Write integration tests for adding new product.
- [ ]  Perform security testing to ensure data protection and compliance.

###Testing 

- Write unit tests for backend validation.
- Write integration tests for the end-to-end add product.
- Perform security testing to ensure data protection and compliance.
- Test various scenarios to adding new product

###

**Comment by markessien** [comment]
good ticket

**Comment by PrudentBird** [comment]
### TEAM PROD

**Members** 

> [PrudentBird](https://github.com/PrudentBird) - NodeJS (NestJS)
> [Oracus](https://github.com/ezeanyimhenry) - PHP
> [Oluwaschunne](https://github.com/Oluwaschunne) - Python (FastApi)

**Comment by PrudentBird** [comment]
**Still being actively worked on by TEAM PROD**

**Comment by buka4rill** [comment]
@PrudentBird this issue is not for your team. None of you had a had creating this

**Comment by buka4rill** [comment]
Please remember to version the api

**Comment by buka4rill** [comment]
@Timmy-id why did you close this ticket?

**Comment by buka4rill** [comment]
wasn't your fault...sorry

**Comment by Obianuju1998** [comment]
### ISSUE TEAM MEMBER

**Members** 

> [Trini7y](https://github.com/Trini7y)
> [muhammad235](https://github.com/muhammad235) 
> [akinwalexander](https://github.com/akinwalexander)
