### ISSUE TITLE
[FEAT] User Status Filtering for Organizations - BACKEND

### ISSUE THREAD

**Issue by Laban254** [hngprojects/hng_boilerplate_nestjs#95]
**Description:**
 Implement filtering for users in an organization based on their status (members, suspended, left workspace).

**Acceptance Criteria:**

1.  **Filtering:**
    
    -   Implement server-side logic to handle filtering users by their status (members, suspended, left workspace).
2.  **User Preferences:**
    
    -   Store user status details securely in the database.
    -   Handle user-specific configurations and preferences related to the filtering process.
3.  **Error Handling:**
    
    -   Log errors for invalid filter requests.
    -   Display clear error messages for invalid inputs.
4.  **Security Measures:**
    
    -   Use HTTPS for secure data transmission.
    -   Validate user input on the server side.

**Purpose:**
 To filter users securely and efficiently, ensuring accurate and safe user management.

**Requirements:**

-  [ ] Develop server-side logic to handle user filtering.
-   [ ] Securely store user status details in the database.
-   [ ] Ensure compliance with security standards for handling user information.

**Expected Outcome:**

-   The backend should handle user filtering securely and efficiently.
-   The system should log errors and handle invalid requests appropriately.

**Endpoints:**

1.  **Fetch Users in Organization:**
    -   **Description:** Provide a list of users based on filter criteria within a specific organization with pagination support.
    -   **Endpoint:** `GET /api/v1/organizations/{organization_id}/users`
    -   **Request Headers:**
        -   `Authorization: Bearer <token>` (required)
        -   `Content-Type: application/json`
        -   `Accept: application/json`
    -   **Request Parameters:**
        -   `status` : `string` (values: `members`, `suspended`, `left`)
        -   `page`: `integer` (optional, `default: 1`)
        -    `limit:` `integer` (optional, `default: 10`)
    -   **Request Example:**

        
        ```json 
             GET /api/v1/organizations/123/users?status=members&page=1&limit=10 HTTP/1.1
             Host: example.com
             Authorization: Bearer <token>
             Content-Type: application/json
             Accept: application/json


     **Response Example:**
    -   **Response (Success):**
        -   **Status Code:** `200 OK`
        -   **Response Body:**

          ```json
               {
                  "total": "integer",
                  "page": "integer",
                  "limit": "integer",
                  "prev": "string or null",
                  "next": "string or null",
                  "users": [
                      {
                        "id": "String",
                        "email": "String",
                        "name": "String",
                        "role": "String",
                        "signup_type": "String",
                        "is_active": true,
                        "is_verified": true,
                        "created_at": "Date",
                        "updated_at": "Date",
                        "last_login_at": "Date",
                        "status": "String"
                     }
                  ]
                }


            
    -   **Response (No Users Found):**
        -   **Status Code:** `404 Not Found`
        -   **Response Body:**
            
  
            
             ```json
               {
              "message": "No users found",
              "statusCode": 404
              }
            
    -   **Response (Invalid Status):**
        -   **Status Code:** `400 Bad Request`
        -   **Response Body:**

             ```json
            {
              "message": "Invalid status value",
              "statusCode": 400
            }
            
    -   **Response (Unauthorized):**
        -   **Status Code:** `401 Unauthorized`
        -   **Response Body:**
            
      
             ```json
            {
              "message": "Unauthorized",
              "statusCode": 401
            }
            
    -   **Response (Internal Server Error):**
        -   **Status Code:** `500 Internal Server Error`
        -   **Response Body:**
            
          
             ```json
            {
              "message": "Internal server error",
              "statusCode": 500
            }
            

**Tasks:**

-  [ ] Create an endpoint `GET /api/v1/organizations/{organization_id}/users` to fetch users based on filter criteria.
-  [ ]  Validate user input on the server side.
-  [ ]  Implement server-side logic to handle successful and failed filter requests.
-  [ ]  Ensure all sensitive data is encrypted and secure.
-  [ ]  Implement logging for errors and filter attempts.
-  [ ]  Write tests for the user filter endpoint.
-  [ ]  Perform security testing to ensure data protection and compliance.

**Testing:**

-  [ ]  Write unit tests for backend validation and filter handling.
-  [ ]  Write integration tests for the end-to-end filter process.
-  [ ]  Perform security testing to ensure data protection and compliance.
-  [ ]  Test various scenarios for user filtering (e.g., valid status, invalid status).

**Comment by markessien** [comment]
Duplicated

**Comment by Laban254** [comment]
@markessien    This issue continues from issue https://github.com/hngprojects/hng_boilerplate_nestjs/issues/66 which has been closed.

**Comment by Laban254** [comment]
Team   TechTitans slack id:
@kibe - Python
@KingTsonga - Java
@Japhet Paul - PHP
@EAZYLINK - Javascript
@Cliff - c#

**Comment by Laban254** [comment]
Hello @Popsicool @buka4rill,

I have completed the implementation for this issue and received the first approval. Could you please review  and provide the second approval at your earliest convenience?

Thank you!

**Comment by Popsicool** [comment]
What is the "last_login_at": "Date" in the response?

**Comment by Laban254** [comment]
It's okay, @Popsicool. I'm working on it.

**Comment by Laban254** [comment]
@Popsicool  Done

**Comment by Popsicool** [comment]
Alright, add pagination to it

**Comment by Popsicool** [comment]
Add next and prev to your response

**Comment by Laban254** [comment]
Okey

**Comment by Laban254** [comment]
@Popsicool  Done with adding next and prev to the response

**Comment by Popsicool** [comment]
cool
