### ISSUE TITLE
[FEAT]: Send Subscription Cancellation Confirmation - Backend 

### ISSUE THREAD

**Issue by Ayobamidele** [hngprojects/hng_boilerplate_nestjs#98]
### Description
<hr>
Implement a feature to send Subscription Cancellation Confirmation to users. This endpoint should immediately update users about the Subscription Cancellation Confirmation details in the system. Upon being successfully sent, it will return the message confirming it is being delivered with a '200' status. If an error occurs, an appropriate error status will be returned.

### Acceptance Criteria
<hr>

- Subscription must already be canceled

 
### Purpose
<hr>
Users get a record/notification of their subscription cancellation confirmation

### Requirements
<hr>

- [x] Subscription exists and has been canceled.
- [x] Ensure only authorized users have access to the endpoint.

## Endpoints
     [POST] /api/v1/user/subscription/notification/cancellation/{id}

**Requests**
```
POST /api/v1/user/subscription/notification/cancellation/{id}
Content-Type: application/json
Authorization: Bearer <access_token>

{
    "id": 1
}

```

**Successful Response**

- Status code: 200

```json
     {
           "message": "Sent Subscription Cancellation Confirmation notification successfully",
           "name": "str",
           "subscription": {
               "id": "int",
               "plan": "str",
               "cancellation_date": "str"
           }
       }
```

**Error Response**

401 **Unauthorized**
```
{
  "status":  "Unauthorized",
  "message":  "Unauthorized. Please log in."
  “status-code”: 401
}
```

400 **Bad Request**
```
{
  "status":  "Bad Request",
  "message":  "Please check the submitted data"
  “status-code”: 400
}
```
404 **No subscription matches id.**
```
{
  "success": false,
  "message": "No Subscription Found",
  "status_code": 404
}
```
500 **Internal Server Error**

```
{
  "success": false,
  "message": "string",
  "status_code": 500
}
```

### Database design

schema

Table name: **Subscription**

id:

    constraints: string(uuid), unique, primary-key, not null

user_id:

    constraints: integer, not null

plan:

    constraints: string, not null, length(150)

is_active:
    
     constraint: boolean

cancelled_at:

    constraints: string, date timestamp

createdAt:

    constraints: string, date timestamp
     

**Tasks**:
 

- [x] Create the endpoint: `[POST] /api/v1/user/subscription/notification/cancellation/{id}`
- [x] Implement the server-side logic to handle subscription cancellations. This includes sending the confirmation notification.
- [x]  Set up logging to capture errors and notification attempts.
- [x]  Write unit tests to verify that the cancellation confirmation is sent correctly.

**Testing**:
   - [x] unit tests, cover scenarios such as valid subscription IDs, invalid subscription IDs, and edge cases.
   - [x] For security testing, consider aspects like input validation and authorized users.

**Comment by markessien** [comment]
This focuses on the email when that is the least of the issues with cancelling a sub

**Comment by Ayobamidele** [comment]
updated

**Comment by phurhard** [comment]
Are the other endpoints under subscription having same URI collection??

**Comment by Ayobamidele** [comment]
yes

**Comment by phurhard** [comment]
@Shullyd7 please check the Uri or this and #168 which one makes more sense

**Comment by Shullyd7** [comment]
@phurhard the one in #168 is cleaner and makes more sense

**Comment by Ayobamidele** [comment]
@Shullyd7 please what are some correction i can make?

**Comment by Shullyd7** [comment]
id should be a path variable, not query parameter @Ayobamidele

**Comment by Ayobamidele** [comment]
@Shullyd7 Thanks Shully, I've made the changes.

**Comment by Ayobamidele** [comment]
Team DataFlow
SlackID
@is_oluwadara nest_js
@bami -Fast api

Mentors pls help review
@AviOfLagos
@prondubuisi

**Comment by max-out-oluwadara** [comment]
Team DataFlow
SlackID
@is_oluwadara - nest_js
@bami - Fast API
