### ISSUE TITLE
[FEAT]API Endpoint for Password Update - BACKEND

### ISSUE THREAD

**Issue by King-AJr** [hngprojects/hng_boilerplate_nestjs#99]
## Description
Create an API endpoint that allows users to update their passwords with input validation and proper security measures.

## Acceptance Criteria
* The endpoint should be accessible at POST /api/password-update.
* The endpoint should accept HTTP POST requests.
* The endpoint should be secured to ensure that only authenticated users can update their passwords.
* Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header. Authorization: Bearer `<token>`
* **Request body**
 ```
{
  "current_password": "CurrentPassword123",
  "new_password": "NewPassword123"
}
```
* **Response**
- On a successful change of the password, the API should return a 201 Created status code.
-  The response body should contain status  and a message
```
{
  "status": "success",
  "message": "Password updated successfully"
}
```
* **Validation**
- If any required field is missing or invalid, the API should return a 400 Bad Request status code with appropriate validation error messages.

```
{
  "status": "unsuccessful",
  "message": "field must be provided"
 }
 ```
 - If the current password is invalid, THE API should return a 400 Bad Request status code with the appropriate message.
 ```
 {
  "status_code": 400,
  "message": "Current password is incorrect"
}
```
- If the new password is weak, the API should return a 400 Bad Request status code with the appropriate message.
```
{
  "status_code": 400,
  "message": "New password does not meet security requirements",
  "error": "Bad Request"
}
```

### Purpose
Provides a secure backend service that allows users to update their passwords.

### Requirements	
* Develop server-side logic to update the user’s password.
* Securely handle password updates and comply with security standards.
* Ensure that password updates are logged and monitored.

### Expected Outcome
* API endpoint allows users to update passwords with appropriate validation and security measures.

###  Tasks
- [x]  Define the server-side application's POST /api/password-update route.
- [x]  Ensure requests include a valid token in the Authorization header.
- [x]  Validate that both current_password and new_password are provided.
- [x]  Ensure new_password meets security requirements.
- [x]  Implement logic to verify the current password.
- [x]  Update the password if it is valid and meets security requirements.
- [x]  Handle cases where the current password is incorrect or the new password does not meet security standards.

### Testing
* Write unit tests to validate input validation and password update logic.
* Write integration tests to ensure end-to-end functionality.
* Perform security testing to ensure data protection and compliance.

**Comment by nedssoft** [comment]
@King-AJr please update the issue to conform with the accepted conventions

**Comment by King-AJr** [comment]
I've edited the response objects to use the snake case, and the endpoint to use the kebab case.

**Comment by buka4rill** [comment]
Please add your teammates slack names and github names in the comment

**Comment by buka4rill** [comment]
Make sure to version your api endpoints

**Comment by King-AJr** [comment]
Slack ID.  -  Github name
@King AJ - King-AJr
@Israel_B.O - IsraelBO17
@Olutayo O. - t33w411
@CodieEmma - merison200

**Comment by King-AJr** [comment]
> Make sure to version your api endpoints

Will do

**Comment by IsraelBO17** [comment]
@IsraelBO17

**Comment by merison200** [comment]
❤️

**Comment by t33w411** [comment]
Let's do this.
